### ISSUE TITLE
Tag validation 

### ISSUE THREAD

**Issue by balloob** [keesschollaart81/vscode-home-assistant#1058]
So this automation in automations.yaml throws a validation error on tag ID. It incorrectly assumes that tag IDs have a specific string format (they should be just strings).

```YAML
automation:
- id: "1613759208429"
  alias: Tag Movie is scanned
  description: ""
  trigger:
    - platform: tag
      tag_id: 04-B1-C6-62-2F-64-80
```

Screenshot from VS Code add-on:
![image](https://user-images.githubusercontent.com/1444314/111088919-b6412800-84e6-11eb-8364-78de0538e771.png)

But... I can't find that annotation in the trigger schema nor can I see it ever being there in the history (and so already fixed). 

Tag schema is here https://github.com/keesschollaart81/vscode-home-assistant/blob/dev/src/language-service/src/schemas/integrations/triggers.ts#L402-L406
