### ISSUE TITLE
Esphome yaml lambda error

### ISSUE THREAD

**Issue by Salvora** [keesschollaart81/vscode-home-assistant#1139]
esphome yaml lambda code like given below gives parse error like below:

`unknown tag <!lambda>YAML`

However, the code runs just fine. It is kind of a special case so I didn't know where to raise this issue.

```YAML
your:
api:
  services:
  - service: ee1_set_intensity
    variables:
      display_intensity: int
    then:
      - globals.set:
          id: display_intensity
          value: !lambda 'return display_intensity;'

  - service: ee1_set_display_mode
    variables:
      display_mode: int
    then:
      - globals.set:
          id: display_mode
          value: !lambda 'return display_mode;'
```

The **value: !lambda** gives error.
