### ISSUE TITLE
Changing quotes not like the standard

### ISSUE THREAD

**Issue by SteffenM-DE** [keesschollaart81/vscode-home-assistant#114]
Hi,
the addon change quotes not like the standard explain for example here [https://developers.home-assistant.io/docs/en/documentation_standards.html](url) or showed at the docu. For example:

At the doc we saw:
```
tts:
  - platform: google_translate
    language: 'de'

```
But I can not insert this, because after saving it looks that:
```
tts:
  - platform: google_translate
    language: "de"

```
This working too but I have something like that:
```
sensor.sql_dbsize_hassiorecorder:
  friendly_name: 'DB Größe (SMCBS002S\hassiorecorder)'
  icon: mdi:database
  unit_of_measurement: MB

```
Chnaging here from quotes to double quotes do not work anymore because it is interpret as escape character.
 
I have some parts the addon change the quotes so code do not work correct. It would be nice to we can influence the behavior.

Regards, Steffen
