### ISSUE TITLE
Incorrect type. Expected "string" on MQTT binary sensor

### ISSUE THREAD

**Issue by snakuzzo** [keesschollaart81/vscode-home-assistant#1148]
Hi everyone.
I've some binary_sensr MQTT entities with a boolean payload on/off  

This is the message published on MQTT broker...

`zigbee2mqtt/mywindow {"battery":97,"contact":true,"linkquality":72,"temperature":24,"voltage":2995}`

...and this is my `binary_sensor`...

```yaml
binary_sensor:

  - platform: "mqtt"
    name: "mywindow"
    state_topic: "zigbee2mqtt/mywindow"
    availability_topic: "zigbee2mqtt/bridge/state"
    value_template: "{{ value_json.contact }}"
    payload_on: false
    payload_off: true
    device_class: "window"
```

No problem on Home Assistant, but HA Helper shows errors like this....

```json
{
	"resource": "/mnt/qnap-myshare/homeassistant/packages/zigbee2mqtt.yaml",
	"owner": "_generated_diagnostic_collection_name_#0",
	"severity": 8,
	"message": "Incorrect type. Expected \"string\".",
	"source": "yaml-schema: http://schemas.home-assistant.io/integration-homeassistant-packages",
	"startLineNumber": 101,
	"startColumn": 17,
	"endLineNumber": 101,
	"endColumn": 22
}
```

@

**Comment by frenck** [comment]
This is actually correct behavior, `payload_on` and `payload_off` are strings by specification, not booleans as in your example, see documentation here:

<https://www.home-assistant.io/integrations/binary_sensor.mqtt/#payload_on>

![image](https://user-images.githubusercontent.com/195327/114546997-1fd76200-9c5e-11eb-85b8-53b61073c316.png)

**Comment by snakuzzo** [comment]
Sorry for the issue...
I opened a new feature on Zigbee2mqtt project.
I solved this way...

```yaml
  - platform: "mqtt"
    name: "mywindow"
    state_topic: "zigbee2mqtt/mywindow"
    availability_topic: "zigbee2mqtt/bridge/state"
    value_template: "{{ 'true' if value_json.contact == true else 'false' }}"
    payload_on: "false"
    payload_off: "true"
    device_class: "window"
 ```
