### ISSUE TITLE
Scene "shorthand" notation shows schema error

### ISSUE THREAD

**Issue by hmmbob** [keesschollaart81/vscode-home-assistant#1212]
The HA Config Helper throws a scheme error if you use "shorthand notation" in scenes:

![image](https://user-images.githubusercontent.com/33529490/118270838-d7130300-b4c0-11eb-9919-cbdb6aba52b9.png)

[According to the docs](https://www.home-assistant.io/integrations/scene/), this is allowed notation.

```YAML
# scenes.yaml
- name: Etenstijd
  id: etenstijd
  entities:
    light.eetkamer_level:
      state: "on"
      brightness: 255
- name: Avond
  id: avond
  entities:
    switch.grijze_lamp: "on"
    switch.staande_lamp: "on"
    switch.window: "on"
- name: "Alles uit"
  id: allesuit
  entities:
    light.eetkamer_level: "off"
    switch.grijze_lamp: "off"
    switch.staande_lamp: "off"
    switch.window: "off"
```

Repo @ https://github.com/hmmbob/HomeAssistantConfig
