### ISSUE TITLE
String does not match the pattern of input_datetime

### ISSUE THREAD

**Issue by Mariusthvdb** [keesschollaart81/vscode-home-assistant#1293]
After reading 1 & 2 👆, type your issue here and please include the related YAML code like this:

```YAML
    trigger:
      - platform: time
        at: '10:00'
```

<img width="989" alt="Schermafbeelding 2021-06-11 om 12 02 49" src="https://user-images.githubusercontent.com/33354141/122031153-bb0bc580-cdce-11eb-920b-26bbbca8280b.png">

while HA documentation states this explicitly to be accepted: https://www.home-assistant.io/docs/automation/trigger/#time-string
