### ISSUE TITLE
Incorrect type: expected "string" on a correct anchor

### ISSUE THREAD

**Issue by Mariusthvdb** [keesschollaart81/vscode-home-assistant#1294]
After reading 1 & 2 👆, type your issue here and please include the related YAML code like this:

```YAML
sensor:

  - platform: template
    sensors:

      presence_icon:
        friendly_name: Presence icon
        value_template: &icon
          >
            {% set presence = states('sensor.family_home') %}
            {% set mapper = {'0':'mdi:account-off',
                             '1':'mdi:account',
                             '2':'mdi:account-multiple',
                             '3':'mdi:account-multiple-check'} %}
            {{mapper[presence] if presence in mapper else 'mdi:account-group'}}
        icon_template: *icon
```

rendering all that precedes this in the yaml as Red, see: https://community.home-assistant.io/t/home-assistant-community-add-on-visual-studio-code/107863/425
<img width="606" alt="Schermafbeelding 2021-06-11 om 11 58 03" src="https://user-images.githubusercontent.com/33354141/122031568-1dfd5c80-cdcf-11eb-9340-eead2b903764.png">

not sure if it isnt the multi-line > that causes the issue here, using it like this (another, but identical error causing anchor + template)

<img width="984" alt="Schermafbeelding 2021-06-15 om 13 47 50" src="https://user-images.githubusercontent.com/33354141/122047486-830d7e00-cde0-11eb-9171-c1c1b179c3a4.png">

the error disappears. Do note the VSC editor doesnt understand the icon_template....
