### ISSUE TITLE
Blueprint selector:select:options

### ISSUE THREAD

**Issue by SirGoodenough** [keesschollaart81/vscode-home-assistant#1295]
This may well be a schema error but I cannot figure out how to fix that, but I will report what I see here anyway.

In setting up a blueprint, I used the select selector.  The code in the blueprint functions correctly in Home Assistant, but an error is reported in the VS-Code add-on.

Blueprint excerpt:
```yaml
  domain: automation
  input:
    speaker_gender:
      name: Speaker Gender
      description: Select speaker gender male or female
      default: male
      selector:
        select:
          options:
            - female
            - male
    speaker_language:
      name: Speaker Language
      description: Select Language code.  See-> https://www.nabucasa.com/config/tts/
      default: en-AU
```
![Screenshot_2021-06-16_03-33-39](https://user-images.githubusercontent.com/47349533/122186546-c0f7ba00-ce53-11eb-93a3-4f1678649efc.png)

Error is:
```Array has too many items. Expected 1 or fewer.```
It appears the list wants to be 1 item under the options: keyword.

Since the blueprint works and since I **believe** I have the correct syntax as per https://www.home-assistant.io/docs/blueprint/selectors/#select-selector I think this is a problem with this vs-code extension in some way.

The entire blueprint is functioning correctly for me and can be found at:  https://community.home-assistant.io/t/door-open-tts-cloud-say-announcer-nabu-casa-required/316046

My HA Config is here:  https://github.com/SirGoodenough/Home-Assistant-Config
