### ISSUE TITLE
automation event trigger schema should allow 'context: > user_id: > String | String[]'

### ISSUE THREAD

**Issue by grillp** [keesschollaart81/vscode-home-assistant#1327]
In the UI you can add context to a trigger (e.g. which user generate the event) to filter the automation to run only for a specific user. This generates a valid `automation.yaml` file that works as expected, but the schema validation in  vs-code addon shows an error at the 'context:' entry:

`Property context is not allowed.yaml-schema: http://schemas.home-assistant.io/integration-automation`

```YAML
- id: '1619006716292'
  alias: 'iOS: Fred's light'
  description: Action to turn on Freds's bedside light from iOS
  trigger:
  - platform: event
    event_type: ios.action_fired
    event_data:
      actionName: bedside_light
    context:
      user_id:
      - 2cddf860e78d47ff9345685fcf837aae
```
