### ISSUE TITLE
Property unique_id is not allowed for Template Weather Provider

### ISSUE THREAD

**Issue by definitio** [keesschollaart81/vscode-home-assistant#1375]
```YAML
weather:
  - platform: template
    unique_id: foobar
    ...
```

```
Property unique_id is not allowed.
```

https://www.home-assistant.io/integrations/weather.template/#unique_id
