### ISSUE TITLE
"Property trace is not allowed" under automation

### ISSUE THREAD

**Issue by TomBrien** [keesschollaart81/vscode-home-assistant#1386]
The option to set the number of traces stored for an automation, as introduced in home-assistant/core#49728 is not recognised. This is admittedly poorly/not documented anywhere on the main HA site I could find (will be fixing that soon)

```yaml
automation:
  ...
  - alias: 123
    trace:
      stored_traces: 20  # Some number
    trigger:
    ...
    action:
    ...
```

![image](https://user-images.githubusercontent.com/12411302/125449093-6d50304b-ea8f-4684-8f58-28406114fc01.png)

I tried to implement the fix myself but my dev machine is headless and I couldn't set up the extension development environment to test the changes.
