### ISSUE TITLE
MQTT alarm_control_panel support

### ISSUE THREAD

**Issue by realthk** [keesschollaart81/vscode-home-assistant#1430]
This is a [valid mqtt `alarm_control_panel`](https://www.home-assistant.io/integrations/alarm_control_panel.mqtt/) config:
```YAML
alarm_control_panel:
  - platform: mqtt
    name: "Security System Partition 1"
    state_topic: "dsc/Get/Partition1"
    availability_topic: "dsc/Status"
    command_topic: "dsc/Set"
    payload_disarm: "1D"
    payload_arm_home: "1S"
    payload_arm_away: "1A"
    payload_arm_night: "1N"
```
but since it is probably taken as non-mqtt `alarm_control_panel`, its `command_topic` is rejected by the parser, so my `configuration.yaml` is also marked as wrong:

![mqtt_alarm](https://user-images.githubusercontent.com/5654575/126805405-a19c5ea2-9893-4f6f-863a-d05926174d28.png)
