### ISSUE TITLE
time: selector in blueprint imports as time: {} and vscode complains

### ISSUE THREAD

**Issue by SirGoodenough** [keesschollaart81/vscode-home-assistant#1481]
When creating a blueprint using the time selector, the docs say it should look like this:
```yaml
    fan_off_time:
      name: Time of day fan should stop
      description: Set this for the time of day you want the fan function to end.
      selector:
        time:
```
That seems to work properly when manually typed in as a Blueprint.

When this is parsed and imported to an actual blueprint using the HA import tool, it arrives like this with {} curly brackets in tow:
```yaml
    fan_off_time:
      name: Time of day fan should stop
      description: Set this for the time of day you want the fan function to end.
      selector:
        time: {}
```
Now all still works correctly, however vsCode reports an incorrect type error.
So is this a schema problem or an import problem, I don't know.

![Screenshot_2021-08-04_03-39-42 1](https://user-images.githubusercontent.com/47349533/128153424-c5160c15-091d-4cc5-80bf-7bf8c535fca2.png)

The blueprint in question is : 
https://community.home-assistant.io/t/auto-fan-temperature-control-for-3-speed-fan-ifanxx-tasmota/326419
OR
https://gist.github.com/SirGoodenough/15003002fc5409f029f38914876fa728
