### ISSUE TITLE
Support for generated device automations

### ISSUE THREAD

**Issue by magnusoverli** [keesschollaart81/vscode-home-assistant#156]
When editing device automations in VSCode, it complains about multiple unsupported entries; `Value is not accepted`, `Property domain is not allowed` and `Property type is not allowed`.

<img width="685" alt="Screenshot 2019-11-07 at 09 12 27" src="https://user-images.githubusercontent.com/3475247/68372011-55f6e500-0140-11ea-93c1-b4a0357523a9.png">

Relevant YAML code:
```YAML
- id: '1573065341392'
  alias: Badelys Auto Av
  description: ''
  trigger:
  - device_id: ed3ef7ed848c4ad9935d9c60665221e2
    domain: binary_sensor
    entity_id: binary_sensor.aeon_labs_zw100_multisensor_6_sensor
    for:
      hours: 0
      minutes: 2
      seconds: 0
    platform: device
    type: turned_off
  condition:
  - condition: state
    entity_id: binary_sensor.dusj
    state: 'off'
    for:
      hours: 0
      minutes: 0
      seconds: 25
  action:
  - data:
      entity_id: light.bad
    service: light.turn_off
```
