### ISSUE TITLE
Bad Indentation of a mapping entry

### ISSUE THREAD

**Issue by DavidFW1960** [keesschollaart81/vscode-home-assistant#159]
Please include the related YAML code

```YAML
yeelight:
  devices:
    !secret yeelight_fan:
      name: Fan Light
    !secret yeelight_meals:
      name: Meals Area Light
```
![image](https://user-images.githubusercontent.com/36390762/68988124-c0b5c800-0886-11ea-9399-1f58cb18f803.png)

It works in HA fine.
or point to a repository containing your Home Assistant Configuration
