### ISSUE TITLE
Quoted service / entity_id not auto-completed

### ISSUE THREAD

**Issue by Chris-V** [keesschollaart81/vscode-home-assistant#167]
I recently installed this extension and noticed I cannot quote any identifiers. I have well dozens of yaml files and every string is quoted (personal preference). I would really like to use the extension without going through all my config to remove the quotes :)

Quoted identifiers don't have suggestions available:
![image](https://user-images.githubusercontent.com/1116964/69456484-c012ab00-0d38-11ea-97d4-42fb354ded2a.png)
![image](https://user-images.githubusercontent.com/1116964/69461216-07eaff80-0d44-11ea-804b-eb7385791585.png)

Unquoted identifiers DO have suggestions available:
![image](https://user-images.githubusercontent.com/1116964/69456551-e9333b80-0d38-11ea-816f-299538de3c5d.png)
![image](https://user-images.githubusercontent.com/1116964/69456921-e127cb80-0d39-11ea-95e6-99a0eadcdbe8.png)

Please include the related YAML code

```YAML
automation:
  - alias: "carl_wake_up"
    trigger:
      - platform: "time"
        at: "8:00:00"
    action:
      - service: "switch.turn_on"
        entity_id:
          - "switch.carl_heater"
          - "switch.carl_uv_light"
```

or point to a repository containing your Home Assistant Configuration
