### ISSUE TITLE
Possible erroneous yaml code error.

### ISSUE THREAD

**Issue by cableghost** [keesschollaart81/vscode-home-assistant#170]
I attempted to see if this is a typical YAML code error via Ctrl+K M, but only the extensions were shown.

Here's the code added to my config file:

```YAML
scene:
  - platform: lifx_cloud
    token: c_my_token
```

Screenshot of error (I've changed my LIFX Cloud token):

![lifx_token_errors](https://user-images.githubusercontent.com/5576447/69572221-4c1b1180-0f89-11ea-8be7-382f48762fad.jpg)
