### ISSUE TITLE
Missing property "state_filter" for Picture Glance Card

### ISSUE THREAD

**Issue by definitio** [keesschollaart81/vscode-home-assistant#173]
```YAML
      - type: picture-glance
        title: Камера 1
        entities:
          - binary_sensor.cam_1_motion_detected
        camera_image: camera.cam_1
```

Got `Missing property "state_filter".` error, although it is optional variable.
