### ISSUE TITLE
unknown tag <!file>

### ISSUE THREAD

**Issue by haakonstorm** [keesschollaart81/vscode-home-assistant#176]
After reading 1 & 2 👆, type your issue here and please include the related YAML code like this:

```YAML
- url: !file '/community_plugin/bignumber-card/bignumber-card.js'
  type: js

   - yaml
```

I'm using the extra tags that come from card-tools I think it is, or declutter card, from thomas loven. But the tag !file is not recognized. Anything to do about this?
