### ISSUE TITLE
Home Assistant Cast row improperly shows errors in Entities Card

### ISSUE THREAD

**Issue by rpitera** [keesschollaart81/vscode-home-assistant#180]
Please include the related YAML code:

 ```
     - type: entities
       entities:
         - type: cast
           name: CameraCast
           view: 18
           hide_if_unavailable: true 
```
                    

According to [this blog post](https://www.home-assistant.io/blog/2019/08/06/home-assistant-cast/#coming-soon-and-future-plans), this is correctly formatted but it shows the following errors:

![error](https://user-images.githubusercontent.com/19910294/70344071-cfa8ee00-1826-11ea-9c84-71d7f61bae28.png)

Extension runs in:
- [] VS Code for Desktop 
- [X] Hassio Add-on 
- [ ] Visual Studio Online
- [ ] Other: 

I'm running VS Code on:
- [ ] Windows 
- [] Mac 
- [X] Linux 

I'm accessing my files:
- [X] From local disk 
- [ ] Via remote SSH 
- [ ] Smb
- [ ] Other:
