### ISSUE TITLE
Property warnings in buttons nested in entities overview

### ISSUE THREAD

**Issue by hmmbob** [keesschollaart81/vscode-home-assistant#1808]
VS Code tells me that properties `show_name`, `tap_action` and `hold_action` aren't allowed, while they're [listed as allowed in the docs](https://www.home-assistant.io/lovelace/entities/#buttons). Had a look at how to fix this myself, but this is outside my comfort zone.

```YAML
      - type: entities ## Oogopslag overview
        entities:
          - type: buttons
            entities:
              - entity: switch.overkapping
                show_name: true
              - entity: switch.genie
                show_name: true
              - entity: switch.aquarium
                show_name: true
          - type: buttons
            entities:
              - entity: switch.zoutlamp
                show_name: true
              - entity: light.sonoff_l1
                show_name: true
                tap_action:
                  action: more-info
                hold_action:
                  action: toggle
```

![image](https://user-images.githubusercontent.com/33529490/147487446-87ae0eaa-1a0a-4d66-a17f-763de422756c.png)
