### ISSUE TITLE
Error: Property stat_types is not allowed.

### ISSUE THREAD

**Issue by sethiele** [keesschollaart81/vscode-home-assistant#1975]
Hi there,
I get this error Message

`Property stat_types is not allowed.yaml-schema: http://schemas.home-assistant.io/lovelace-views`

Code:
```YAML
title: Wetter
path: weather
icon: mdi:white-balance-sunny
cards:
  - type: statistics-graph
    entities:
      - sensor.luftdaten_1376_p1
    stat_types:
      - min
      - max
      - mean
    days_to_show: 3
    chart_type: line
```
<img width="237" alt="image" src="https://user-images.githubusercontent.com/254761/159117568-566215ce-0503-4480-8297-1ba4c849dba1.png">

In the schema, it looks fine for me.
https://github.com/keesschollaart81/vscode-home-assistant/blob/3cc61656950eb540c3e08221b222deff90dff7a4/src/language-service/src/schemas/lovelace/cards/statistics_graph.ts#L48-L52

It looks like a Problem for me?

Dan Thanks for your Work!!!
