### ISSUE TITLE
Picture Elements image title: and state-icon icon: not allowed

### ISSUE THREAD

**Issue by matt8707** [keesschollaart81/vscode-home-assistant#200]
Picture Elements image title: and state-icon icon: not allowed

```YAML
views:
  - badges: []
    cards:
      - elements:
      
          - entity: entity
            title: null  #Property title is not allowed.
            type: image

          - entity: entity
            icon: 'mdi:'  #Property icon is not allowed
            type: state-icon

        type: picture-elements
```
