### ISSUE TITLE
input_text reports error when using the 'initial' configuration variable

### ISSUE THREAD

**Issue by cbhiii** [keesschollaart81/vscode-home-assistant#2004]
Using `input_text` reports error when using the `initial` configuration variable. 

I confirmed via step (1) that it seems to be within this repository. I was not able to find the files referenced in step (2). Maybe if I was more tech savvy. At any rate, I hope this helps highlight the issue and resolve it.

YAML text
```YAML
input_text:
    office_light_override:
    name: Office lights override
    initial: "idle"        # Incorrect type. Expected "integer".
    icon: mdi:form-textbox
```

Screenshot
![input text](https://user-images.githubusercontent.com/10853381/160441406-6dd6ea4f-4fc6-437b-91b3-39a7aa4f073c.png)
