### ISSUE TITLE
Modern-style template sensor definition results in linter errors.

### ISSUE THREAD

**Issue by nikipore** [keesschollaart81/vscode-home-assistant#2012]
Modern-style template sensor definitions result in linter errors, no matter whether the `template` key is in `config/configuration.yaml` or in some yaml package.

Add this block to `config/configuration.yaml`:
```yaml
template:
  binary_sensor:
    - name: test
      state: >
        {{ true }}
```

This results in a linter error:
```json
[{
	"resource": "/config/packages/test.yaml",
	"owner": "_generated_diagnostic_collection_name_#0",
	"severity": 8,
	"message": "Incorrect type. Expected \"array\".",
	"source": "yaml-schema: http://schemas.home-assistant.io/integration-homeassistant-packages",
	"startLineNumber": 2,
	"startColumn": 3,
	"endLineNumber": 6,
	"endColumn": 1
}]
```

**Comment by ADobin** [comment]
I've been using a lot of the new template sensor, assuming you are on the latest of this addon I believe that you should be passing the senors as an array and not objects.

```yaml
template:
  - binary_sensor:
    - name: "Test"
      state: >
        {{ true }}
```
In my configuration, this resolves your issue and creates a working sensor.

**Comment by nikipore** [comment]
Thanks. I looked at the documentation. This seems to have been enriched in the meantime. When I started creating template entities, I believe they were defined in a mapping of entity types, not in a list of "sections" or "blocks".

But: In the [documentation](https://www.home-assistant.io/integrations/template/#turning-an-event-into-a-binary-sensor) there is still one example of a mapping left:
```yaml
template:
  trigger:
    platform: event
    event_type: my_event
  binary_sensor:
    - name: Event recently fired
      auto_off: 5
      state: "true"
```

Thus: As long as the documentation allows it explicitly, I still believe this should be accepted as valid Home Assistant YAML.
