### ISSUE TITLE
Blueprint Selector Action shows false syntax error -> Incorrect type. Expected "null".yaml-schema:

### ISSUE THREAD

**Issue by SirGoodenough** [keesschollaart81/vscode-home-assistant#2074]
After reading 1 & 2 👆, type your issue here and please include the related YAML code like this:

When this is set to YAML schema in Code Server, there NO error shown.

When Home Assistant imports a blueprint with an empty action sensor, it adds {} to the end of the line.
The homeassistant extension schema in VSCode complains stating that it is expecting null.
Everything works as is.  Just shows the annoying 'error'. Not really sure if HA should not be adding the {} or if the homeassistant extension should allow {}, but it turns red and shows an 'error' in either case.

The same happens with time {} which shows the same error.

This is how the blueprints import (below), even though it goes in as this (next):

```YAML
      selector:
        action:
```

```YAML
    flipped90_face_0:
      name: Group 1 actions 🍎 Flip the cube 90 degrees to face 0
      description: Face 0 is the one with the 'Aqara' LOGO
      default: []
      selector:
        action: {}
```
error:
Incorrect type. Expected "null".yaml-schema: http://schemas.home-assistant.io/blueprint-automation

And the extension complains like this:

![Screenshot_2022-05-02_19-31-03](https://user-images.githubusercontent.com/47349533/166349666-0035be71-0897-4331-9c6f-11a2d2c024f2.png)
![Screenshot_2022-05-02_19-46-46](https://user-images.githubusercontent.com/47349533/166389366-a861323c-a74a-4230-946d-c4ff43c84b7a.png)

```yaml
    end_time:
      name: EndTime
      description: 'Time of day you want to disable the announcement each day.  Leave
        at 12:00:00 if you want it to always be on.

        '
      selector:
        time: {}
      default: 00:00:00
```
![Screenshot_2022-05-03_02-12-04](https://user-images.githubusercontent.com/47349533/166416489-88eeef97-5f5f-4950-9d49-740020151852.png)

and/or point to a repository containing your Home Assistant Configuration

Example of where I see it in the action selectors:
https://github.com/SirGoodenough/Home-Assistant-Config/blob/master/blueprints/automation/SirGoodenough/Zigbee2MQTT%20-%20Xiaomi%20Cube%20Controller.yaml
