### ISSUE TITLE
Property sequence is not allowed

### ISSUE THREAD

**Issue by definitio** [keesschollaart81/vscode-home-assistant#2094]
```YAML
automation:
  - trigger:
      - platform: state
        entity_id: binary_sensor.motion
        to: "on"
    action:
      - parallel:
          - sequence:
              - wait_for_trigger:
                  - platform: state
                    entity_id: binary_sensor.motion
                    to: "on"
              - service: notify.person1
                data:
                  message: "This message awaited the motion trigger"
          - service: notify.person2
            data:
              message: "I am sent immediately and do not await the above action!"
```
Errors:
```
Missing property "condition".
Missing property "conditions".
Property sequence is not allowed.
```
