### ISSUE TITLE
Error: metadata: {} - Property metadata is not allowed

### ISSUE THREAD

**Issue by oneseventhree** [keesschollaart81/vscode-home-assistant#2120]
VS is showing this error:
<img width="471" alt="Screen Shot 2022-05-22 at 5 43 06 pm" src="https://user-images.githubusercontent.com/15043282/169684453-25c04c22-cfb3-42b7-8c88-de3730b31350.png">

Even though its fine in UI:
<img width="990" alt="Screen Shot 2022-05-22 at 5 45 17 pm" src="https://user-images.githubusercontent.com/15043282/169684503-3df06c5c-0f77-4664-9f05-9e49737b2139.png">

```YAML
 - service: scene.turn_on
    target:
      entity_id: scene.office_play_light_bar_gaming
    metadata: {}
```
