### ISSUE TITLE
Multiple button card errors

### ISSUE THREAD

**Issue by definitio** [keesschollaart81/vscode-home-assistant#2146]
```YAML
  - type: button
    entity: button.pc_lock
    show_name: false
    tap_action:
      action: call-service
      confirmation: true # Incorrect type. Expected "object"
      service: button.press
      data: # Property data is not allowed.
        entity_id: button.pc_lock
```
`confirmation` [can be boolean](https://www.home-assistant.io/dashboards/actions/#confirmation).
`data` should be [allowed](https://www.home-assistant.io/dashboards/actions/#data).
