### ISSUE TITLE
Property segments is not allowed for Gauge Card

### ISSUE THREAD

**Issue by definitio** [keesschollaart81/vscode-home-assistant#2162]
```YAML
      - type: gauge
        entity: sensor.water_pressure
        needle: true
        min: 0.5
        max: 2
        segments:
          - from: 0
            color: "#db4437"
          - from: 0.8
            color: "#ffa600"
          - from: 1
            color: "#43a047"
          - from: 1.5
            color: "#ffa600"
          - from: 1.7
            color: "#db4437"
```
`Property segments is not allowed.`
