### ISSUE TITLE
MQTT Device Tracker - Valid code flagged as invalid

### ISSUE THREAD

**Issue by g4sbq** [keesschollaart81/vscode-home-assistant#2167]
Following recent changes to the MQTT device tracker, valid YAML is flagged with errors...

![image](https://user-images.githubusercontent.com/57624938/173348164-be8bc39e-4c69-4f73-afba-3984df0986c1.png)

Version of VSCode Helper is 1.30.1

```YAML
mqtt:
  device_tracker:
    - name:  "bi_adam"
      state_topic: "blue_iris/sensor/bi_geofence_adam/state"
      payload_home: "home"
      payload_not_home: "away"
   - yaml
```

and/or point to a repository containing your Home Assistant Configuration
