### ISSUE TITLE
Property json_attributes_template is not allowed - in mqtt sensor

### ISSUE THREAD

**Issue by ravensergio** [keesschollaart81/vscode-home-assistant#224]
```YAML
sensor:
  - platform: mqtt
    name: "leddimlevel"
    icon: mdi:brightness-7
    json_attributes_topic: "mydimmer/status/STATUS5"
    json_attributes_template: '{{ value_json["StatusNET"]["IPAddress"] }}'
    state_topic: "mydimmer/status/result"
    value_template: "{{ value_json.Dimmer }}"
    unit_of_measurement: "%"
```
This is a part of my valid config in HA ( I'm using it for a while ,documented in HA docs).
I get this error : "**Property json_attributes_template is not allowed**".
Also, i made some automations in the frontend ( Configuration - Automations- Add automation). 
After doing that, the saved automation in my .yaml file has this error: "**Property alias is not allowed.**"
It is talking about the  **-alias: ''**  line (single quote open-close) that is after ( **-delay**). 
But is in fact ok, I made it via front end as i said, so the automation was wrote in the file by HA, not manually,  and I've been using it for a while.

```YAML
  - id: '1578949847122'
    alias: Delay Start Central
    description: delay in node red
    trigger:
    - event: start
      platform: homeassistant
    condition: []
    action:
    - delay: 00:00:30
    - alias: ''
      data:
        entity_id: input_boolean.delaystart_central
      service: input_boolean.turn_on
```
 I am sorry i don't know how to add these as exception.
Thank you.
