### ISSUE TITLE
Error  concerning "repeat:  for_each:" loop.

### ISSUE THREAD

**Issue by Plazmin** [keesschollaart81/vscode-home-assistant#2252]
![1](https://user-images.githubusercontent.com/62091912/186257465-25953019-610d-4c35-a4c3-44b3a01ac176.png)

```YAML
alias: Demo for each loop
mode: restart
sequence:
  - alias: use a for each loop
    repeat:
      for_each:
        - lounge_lights
        - kitchen_lights
      sequence:
        - service: light.turn_off
          target:
            entity_id: light.{{ repeat.item }}

```
When writing a script in VSCode, errors are reported (with red underline) when the script is valid.
I expect errors only to be indicated when the syntax is incorrect.
