### ISSUE TITLE
Incorrect type. Expected "string". when using badges:

### ISSUE THREAD

**Issue by nambuco** [keesschollaart81/vscode-home-assistant#228]
On my ui-lovelace.yaml I always get "" error message when using badges: with -entity:

See extract from my yaml file:
```
title: Casa
views:
  - title: teste
    badges:
      - binary_sensor.updater
      - entity: binary_sensor.updater
```
The last line trigged the error message, but both syntax are allowed.
