### ISSUE TITLE
mqtt.number not accepting unit_of_measurement

### ISSUE THREAD

**Issue by LeoWinterDE** [keesschollaart81/vscode-home-assistant#2290]
```YAML
mqtt:
  number:
    - name: evcc_min_current
      unique_id: uniqueid__evcc_min_current
      icon: mdi:current-ac
      state_topic: "evcc/loadpoints/1/minCurrent"
      command_topic: "evcc/loadpoints/1/minCurrent/set"
      availability_topic: "evcc/status"
      min: 6
      max: 16
      step: 0.25
      unit_of_measurement: A
```

![bug](https://user-images.githubusercontent.com/1300141/191832212-f335c429-8ca1-40b1-9ed2-7c91ab96ada8.png)
