### ISSUE TITLE
Property alias is not allowed

### ISSUE THREAD

**Issue by oneseventhree** [keesschollaart81/vscode-home-assistant#2293]
Error in HA VSCode:
<img width="571" alt="Screen Shot 2022-09-25 at 3 03 33 pm" src="https://user-images.githubusercontent.com/15043282/192129312-49ade2d8-3f19-46ad-9df5-3be17fcfed8a.png">

```YAML
- id: '1654160093041'
  alias: Holiday Status ON/OFF with Calendar
  description: 'Option 1 - ON

    Option 2 - OFF'
  trigger:
  - platform: template
    value_template: '{{ now()

      >=

      as_local(as_datetime(state_attr(''calendar.holidays'',''start_time'')))

      - timedelta(hours = 3, minutes = 1)


      and(


      now()

      <=

      as_local(as_datetime(state_attr(''calendar.holidays'',''start_time'')))

      - timedelta(hours = 3, minutes = 0, seconds = 55))

      }}'
    id: Holiday - On
    alias: Holiday - On
  - platform: template
    value_template: '{{ now()

      >=

      as_local(as_datetime(state_attr(''calendar.holidays'',''end_time'')))

      + timedelta(hours = 0, minutes = 30)


      and(


      now()

      <=

      as_local(as_datetime(state_attr(''calendar.holidays'',''end_time'')))

      + timedelta(hours = 0, minutes = 30,seconds = 5))

      }}'
    id: Holiday - Off
    alias: Holiday - Off
  condition:
  - condition: not
    conditions:
    - condition: state
      entity_id: input_select.holiday_status
      state: Away
    alias: 'Not: Away'
  action:
  - choose:
    - conditions:
      - condition: template
        value_template: '{{ now()

          >=

          as_local(as_datetime(state_attr(''calendar.holidays'',''start_time'')))

          - timedelta(hours = 3, minutes = 1)


          and(


          now()

          <=

          as_local(as_datetime(state_attr(''calendar.holidays'',''start_time'')))

          - timedelta(hours = 3, minutes = 0, seconds = 55))

          }}'
        enabled: false
      - condition: trigger
        id: Holiday - On
      sequence:
      - service: input_select.select_option
        data:
          option: 'On'
        target:
          entity_id: input_select.holiday_status
      - service: notify.mobile_app_oneseventhree
        data:
          title: Holiday Mode
          message: ACTIVATED due to Holiday tomorrow
          data:
            push:
              sound: CameraCountdownImminent_Haptic.caf
    - conditions:
      - condition: template
        value_template: '{{ now()

          >=

          as_local(as_datetime(state_attr(''calendar.holidays'',''end_time'')))

          + timedelta(hours = 0, minutes = 30)


          and(


          now()

          <=

          as_local(as_datetime(state_attr(''calendar.holidays'',''end_time'')))

          + timedelta(hours = 0, minutes = 30,seconds = 5))

          }}'
        alias: 'Note: Changed to 30 minutes to allow change'
        enabled: false
      - condition: trigger
        id: Holiday - Off
      - condition: state
        entity_id: calendar.holidays
        state: 'off'
      sequence:
      - service: input_select.select_option
        data:
          option: 'Off'
        target:
          entity_id: input_select.holiday_status
      - service: notify.mobile_app_oneseventhree
        data:
          title: Holiday Mode
          message: DEACTIVATED
          data:
            push:
              sound: CameraCountdownImminent_Haptic.caf
    default: []
    alias: 'Option 1: Holiday ON - Option 2: Holiday OFF'
  mode: restart
```
