### ISSUE TITLE
Linter warning for new device_class: water

### ISSUE THREAD

**Issue by saschaludwig** [keesschollaart81/vscode-home-assistant#2353]
2.  Is a HA scheme error?

I'll guess so. But I'm not aware on how to actually fix that.

# Problem/Motivation
add a water meter to your configuration yaml 

## Expected behaviour
linter will not complain about device_type: water

## Actual behaviour
linter will complain about device_type:
![Bildschirmfoto 2022-11-09 um 19 22 10](https://user-images.githubusercontent.com/12997980/200910461-e6048e9c-87c2-441e-9ed4-b6f5189537d0.png)

## Steps to reproduce
add this to your configuration.yaml like stated here: https://github.com/home-assistant/home-assistant.io/issues/24801

```
mqtt:
  sensor:
    # Wasserzaehler
    - name: "Wasserzähler"
      state_topic: "wasserzaehler/main/json"
      value_template: "{{ value_json.value }}"
      unit_of_measurement: "m³"
      state_class: "total_increasing"
      icon: "mdi:water"
      unique_id: "wasserzaehler"
      device_class: water

```
