### ISSUE TITLE
Send_if_off deprecated

### ISSUE THREAD

**Issue by IanAdd** [keesschollaart81/vscode-home-assistant#2355]
<!-- 

After reading 1 & 2 👆, type your issue here and please include the related YAML code like this:

```YAML
mqtt:
  climate:
  - name: OZ_Ensuite_Thermostat
#    send_if_off: false
    availability_topic: "oz_ensuite/tele/LWT"
    payload_available: "Online"
    payload_not_available: "Offline"
    action_topic: "oz_ensuite/stat/things/thermostat/properties"
#    action_template: "{{value_json.action}}"
    action_template: >
      {% if (value_json.targetTemperature|float(0) <= value_json.floorTemperature|float(0)) and value_json.action == 'heating' %}
        idle
      {% else %}
        {{value_json.action}}
      {%endif%}
    temperature_command_topic: "oz_ensuite/cmnd/things/thermostat/properties/targetTemperature"
    temperature_state_topic: "oz_ensuite/stat/things/thermostat/properties"
    temperature_state_template: "{{value_json.targetTemperature}}"
    # set current temp to temp of floor sensor not room temp
    current_temperature_topic: "oz_ensuite/stat/things/thermostat/properties"
    current_temperature_template: "{{value_json.floorTemperature}}"
    mode_command_topic: "oz_ensuite/cmnd/things/thermostat/properties/mode"
    mode_state_topic: "oz_ensuite/stat/things/thermostat/properties"
    mode_state_template: "{{value_json.mode}}"
    payload_on: "true"
    payload_off: "false"
    modes: [ "heat", "auto", "idle", "off" ]
    min_temp: 5
    max_temp: 35
    temp_step: 0.5
    precision: 0.5
```

This entity definitioncauses two errors to be reported in Studio Code Editor
1) It complains that 'send_if_off' is missing but it is deprecated in HA.

2) It complains that "idle" is not valid but I am defining it in my code to exist.
It possible to disable its complaint in this case ?
