### ISSUE TITLE
Add 'country' option to homeassistant section on the config (Home Assistant 2022.12 update)

### ISSUE THREAD

**Issue by appuchias** [keesschollaart81/vscode-home-assistant#2377]
In 2022.12 home assistant added the `country:` setting to the `homeassistant:` section in YAML and I'm getting `property country is not allowed` when setting it.

```YAML
homeassistant:
  name: NAME
  # ...
  country: ISOCODE # Property country is not allowed.
```

Change detailed here: https://www.home-assistant.io/blog/2022/12/07/release-202212/#other-noteworthy-changes
Property information: https://www.home-assistant.io/docs/configuration/basic/#country
