### ISSUE TITLE
Property state_color is not allowed

### ISSUE THREAD

**Issue by definitio** [keesschollaart81/vscode-home-assistant#238]
```YAML
      - type: entities
        title: <title>
        state_color: true
        entities:
          - <entity_id>
```
It's new option: https://www.home-assistant.io/blog/2020/02/05/release-105/#icons-no-longer-change-color-based-on-state
