### ISSUE TITLE
{%Y} messes up syntax highlighting

### ISSUE THREAD

**Issue by mxwi** [keesschollaart81/vscode-home-assistant#2393]
As mentioned here [https://github.com/hassio-addons/addon-vscode/issues/553](https://github.com/hassio-addons/addon-vscode/issues/553)

the addon [Waste Collection Schedule](https://github.com/mampfes/hacs_waste_collection_schedule) accepts [a variable "{%Y}"](https://github.com/mampfes/hacs_waste_collection_schedule/blob/master/doc/source/ics.md#configuration-variables) in the configuration.yaml. This messes up the syntax highlighting.

## Expected behavior

> ![image](https://user-images.githubusercontent.com/32883521/208066651-d65d648f-1e0a-4c7e-9da0-d4a317f00f1c.png)

## Actual behavior

> ![image](https://user-images.githubusercontent.com/32883521/208066705-948379ea-4563-4c10-bf4c-100837aaaf31.png)

Please include the related YAML code:

```YAML
#########################
#   Waste Collection    #
#########################

waste_collection_schedule:
  sources:
    - name: ics
      args:
        url: "http://10.10.1.108:8123/local/Abfuhrkalender-Ehekirchen-{%Y}-full.ics"

#####################
#   Cover Group     #
#####################

cover:
  - platform: group
    name: "Alle Jalousie"
    entities:
      - cover.kuchenjalousie
      - cover.esszimmerjalousie
      - cover.terrassentur
      - cover.terrassenfenster
      - cover.wohnzimmer_west
      - cover.wohnzimmer_sud
  - platform: group
    name: "beide Terrassenfenster"
    entities:
      - cover.terrassentur
      - cover.terrassenfenster
```

Extension runs in:
- [ ] VS Code for Desktop 
- [X] Hassio Add-on 
- [ ] Visual Studio Online
- [ ] Other: 

I'm running VS Code on:
- [ ] Windows 
- [ ] Mac 
- [ ] Linux 

I'm accessing my files:
- [X] From local disk 
- [ ] Via remote SSH 
- [ ] Smb
- [ ] Other:
