### ISSUE TITLE
Unexpected property condition

### ISSUE THREAD

**Issue by tomlut** [keesschollaart81/vscode-home-assistant#24]
"Unexpected property condition" error is reported when conditions are used in automation actions.

**Comment by keesschollaart81** [comment]
Can you share some of the relevant pieces of you configuration?

**Comment by tomlut** [comment]
Sure, here's an example of a condition in an action:

```
  action:
  - service: switch.turn_on
    entity_id: switch.lounge_dehumidifier
  - service: persistent_notification.create
    data_template:
      message: "Lounge room dehumidifier started at {{ now().strftime('%H:%M - %A %d %B %Y') }}. Condensation chance high and outside temperature low."
      title: "Information"
  - condition: state
    entity_id: input_boolean.dnd
    state: "off"
  - service: notify.ios_iphonex
    data:
      message: "Lounge room dehumidifier started. Condensation chance high and outside temperature low."
      data:
        push:
          sound: "DehumidifierActivated.wav"
```

And some scripts with both service and entity errors:

```
cinema_amp_input_pc:
  sequence:
    service: remote.send_command
    data:
      entity_id: remote.cinema_amp
      command: "PC"
```

and another:

```
lounge_cam_snapshot:
  sequence:
    service: camera.snapshot
    data_template:
      entity_id: camera.lounge
      filename: "/config/www/snapshots/lounge_{{now().strftime('%Y-%m-%d-%H-%M-%S') }}.jpg"
```

```
cinema_kodi_input_back:
  sequence:
    service: media_player.kodi_call_method
    data:
      entity_id: media_player.cinema_kodi
      method: Input.Back
```

**Comment by keesschollaart81** [comment]
Yes, these are indeed correct configurations. I fixed the schema's and by now you should be able to update to 0.5.4!

**Comment by tomlut** [comment]
Thanks for the quick response! 

That does indeed look a lot better. Though there are still a few false highlighting of errors in my scripts file:

Unexpected property entity_id, for these
```
away_mode:
  sequence:
  - service: homeassistant.turn_off
    entity_id: automation.7pm_abc_news_on_tv
```
```
internal_siren_1bip:
  sequence:
  - service: switch.turn_on
    entity_id: switch.siren_upstrs
```
```
alarm_arm:
  sequence:
    service: alarm_control_panel.alarm_arm_away
    entity_id: alarm_control_panel.house

alarm_arm_instant:
  sequence:
    service: alarm_control_panel.alarm_arm_away
    entity_id: alarm_control_panel.house
    data:
      code: 'override'

alarm_disarm:
  sequence:
    service: alarm_control_panel.alarm_disarm
    entity_id: alarm_control_panel.house
    data:
      code: !secret alarm_code
```
```
internal_siren_2bip:
  sequence:
  - service: switch.turn_on
    entity_id: switch.siren_upstrs
  - service: input_boolean.turn_on
    entity_id: input_boolean.dummy_delay
  - service: input_boolean.turn_off
    entity_id: input_boolean.dummy_delay
  - service: switch.turn_off
```
The last line of this is expecting a string for the seconds: value, when an integer is correct
```
  - service: light.turn_on
    data:
      entity_id: light.lifx_mstr_bed_1
      kelvin: 2700
      brightness: 170
      transition: 600
  - delay:
      seconds: 600
```
Unexpected property condition, entity_id and state for the last condition in this,
```
lounge_macro_watch_movie:
  sequence:
  - service: remote.send_command
    data:
      entity_id: remote.lounge_tv #TV On
      command: "ON"
  - service: remote.send_command #Amp On
    data:
      entity_id: remote.lounge_amp
      command: "ON"
  - service: remote.send_command #Kodi Sound
    data:
      entity_id: remote.lounge_amp
      command: "MD"
  - delay: 00:00:05
  - service: remote.send_command #Kodi TV input
    data:
      entity_id: remote.lounge_tv
      command: "HDMI2"
  - condition: state
    entity_id: light.rear_and_middle_downlights
    state: 'on'
  - service: input_select.select_option
    data:
      entity_id: input_select.lounge_scene
      option: "Watch Movie"
```

**Comment by keesschollaart81** [comment]
Try again with 0.5.5!

**Comment by tomlut** [comment]
You're a machine Kees! Very fast update.

And happy to report it works perfectly.

Thank you very much for this fantastic extension.

**Comment by spali** [comment]
Have another one:
```yaml
script:
  test_script:
    sequence:
      - service_template: ""
```
reports
```
Missing property "service".
```

sorry for abusing this issue, but it matches good and hope it's not required to create a new one just for this.
