### ISSUE TITLE
Tile Card is not supported

### ISSUE THREAD

**Issue by definitio** [keesschollaart81/vscode-home-assistant#2412]
```YAML
      - type: tile
        entity: sensor.entity_id
        name: Sensor name
```

Error:
```
Value is not accepted. Valid values: "alarm-panel".
```
