### ISSUE TITLE
"Property title not allowed" on vertical-stack Lovelace element

### ISSUE THREAD

**Issue by KalenXI** [keesschollaart81/vscode-home-assistant#247]
Getting a "Property title not allowed" error when setting the title property on a vertical-stack:

```
- type: vertical-stack
      title: Brother Laser Printer
      cards:
      - type: custom:bar-card
        entities:
          - entity: sensor.mfc_9330cdw_cyan_toner_remaining
            color: "#00FFFF"
            title: Cyan
```

The property functions correctly and is a valid property according to the documentation for vertical stack: https://www.home-assistant.io/lovelace/vertical-stack/
