### ISSUE TITLE
mqtt: sensor + binary sensor miss encoding property

### ISSUE THREAD

**Issue by atamgp** [keesschollaart81/vscode-home-assistant#2529]
```YAML
mqtt:
  sensor:
    - name: "solax_test"
      state_topic: "loc/solax_test"
      encoding: ""
```

File to edit:
https://github.com/keesschollaart81/vscode-home-assistant/blob/master/src/language-service/src/schemas/integrations/core/mqtt.ts

Interface **BinarySensorItem** and **SensorItem** here should add this property:

`encoding?: string;`

reference:
https://www.home-assistant.io/integrations/sensor.mqtt/#encoding

I don't have ts and npm stuff installed, sry
