### ISSUE TITLE
Author Tag generates Scheme error

### ISSUE THREAD

**Issue by SirGoodenough** [keesschollaart81/vscode-home-assistant#2599]
After reading 1 & 2 👆, type your issue here and please include the related YAML code like this:

```YAML
blueprint:
  name: Door open tts.cloud_say announcer (Nabu-Casa required) - 2023-03-01
  author: SirGoodenough
  description: 'This uses tts.cloud_say from Nabu-Casa to tell you a door is open too
    long and a door has been closed.
```
The author tag generatesan error in the Schema check. I think this one slipped thru.  I have tried in the past to help with code on these but it is a bit beyond me...
Here's what it does. ->

![Screenshot_20230403_030821](https://user-images.githubusercontent.com/47349533/229452744-08131e27-6aa5-45f9-9ba5-967a39ac6ef9.png)
