### ISSUE TITLE
Copy / Paste indentation incorrect.

### ISSUE THREAD

**Issue by tomlut** [keesschollaart81/vscode-home-assistant#26]
When I copy some configuration to duplicate and edit it, the indentation of the pasted configuration is incorrect. The pasted strings take the indentation of the previous line no matter how many blank lines are in between the copy/paste.

 e.g. copying these two lines of customization yaml,..
```
light.bar_downlights:
  icon: mdi:track-light
```
... and pasting to a blank line below it produces this:

```
light.bar_downlights:
  icon: mdi:track-light

  light.bar_downlights:
    icon: mdi:track-light
```

This makes an absolute mess of copying and pasting Lovelace cards in a stack.
