### ISSUE TITLE
tod incorrect error indicating unique_id invalid

### ISSUE THREAD

**Issue by vlape** [keesschollaart81/vscode-home-assistant#2605]
After reading 1 & 2 👆, type your issue here and please include the related YAML code like this:
I read the links above. yaml-ast-parser is now archived by developer.

When creating a tod sensor, I fet the following:
Error: Property unique_id is not allowed
Per [Docs](https://www.home-assistant.io/integrations/tod/) unique_id is a valid property.
YAML Schema url us invalid. No DNS record for domain. http://schemas.home-assistant.io/integration-homeassistant-packages

```YAML
binary_sensor:
  - platform: tod
    name: REDACTED
    after: "22:00"
    before: "09:00"
    unique_id: REDACTED
```

and/or point to a repository containing your Home Assistant Configuration
![screenshot 2023-04-09 - qpIUOGCj@2x](https://user-images.githubusercontent.com/7841262/230785320-015760b5-8e66-4ef5-b624-d4da2f9e4998.png)
