### ISSUE TITLE
Linter warning for webhook "allowed_methods" and "local_only"

### ISSUE THREAD

**Issue by foxsam21** [keesschollaart81/vscode-home-assistant#2695]
https://www.home-assistant.io/docs/automation/trigger/#webhook-trigger

```YAML
template:
  - trigger:
      - webhook_id: "motion_start"
        id: "on"
        platform: webhook
        allowed_methods:
          - POST
          - PUT
        local_only: true
```
![Screenshot from 2023-06-07 15-52-38](https://github.com/keesschollaart81/vscode-home-assistant/assets/11862524/7c719c51-f8f2-4f7f-a5f8-e12b060b4822)

Prob this:
> 2.  Is a HA scheme error?
>
>    Feel free to fix this yourself, it's quite easy, HowTo here:
>    https://github.com/keesschollaart81/vscode-home-assistant/wiki/HowTo:-Update-the-schema's
I don't know if I have the capabilities to fix it. :(
