### ISSUE TITLE
VSCode Host url goes to file

### ISSUE THREAD

**Issue by moskovskiy82** [keesschollaart81/vscode-home-assistant#2698]
Have set up 
codercom/code-server:latest

Docker compose

```
  vscode:
    container_name: homeassistant-vscode
    image: codercom/code-server:latest
    user: xxx:xxx
    volumes:
      - /xxx:/home/coder/project
      - /xxx:/home/coder/.local/share/code-server
    ports:
      - "8443:8443"
    command: code-server --port 8443 --disable-telemetry /home/coder/project
    environment:
      - PASSWORD=xxx
    restart: unless-stopped

```

Followed the guide and entered the url and token and get the following error. It's the file:///https;// which looks weird to me

Already tried reinstalling

Error connecting to your Home Assistant Server at file:///https;//my URL:8125 and token 'xxx.', check your network or update your VS Code Settings, make sure to (also) check your workspace settings! Error: ERR_CANNOT_CONNECT
