### ISSUE TITLE
Persistent notification trigger

### ISSUE THREAD

**Issue by definitio** [keesschollaart81/vscode-home-assistant#2732]
```YAML
  trigger:
    - platform: persistent_notification
      ...
```

Persistent notification [docs](https://www.home-assistant.io/integrations/persistent_notification/#automation).

Error:
```
Value is not accepted. Valid values: "calendar".yaml-schema: http://schemas.home-assistant.io/integration-automation(1)
```

and/or point to a repository containing your Home Assistant Configuration
