### ISSUE TITLE
Incorrect type. Expected "array".yaml-schema: http://schemas.home-assistant.io/integration-template

### ISSUE THREAD

**Issue by mbo18** [keesschollaart81/vscode-home-assistant#2745]
Hi,
It seems that this extension does not recognize this template schema (which is working fine in HA, no error in logs):

In configuration.yaml:
```YAML
template: !include templates.yaml
```
in templates.yaml:
```YAML
- binary_sensor:
    name: ...
    unique_id: ...
    ...

- binary_sensor:
    name: ...
    unique_id: ...
    ...

- sensor:
    name: ...
    unique_id: ...
    ...

- sensor:
    name: ...
    unique_id: ...
    ...
```

Error is: 
`Incorrect type. Expected "array".yaml-schema: http://schemas.home-assistant.io/integration-template`

Also note that URL http://schemas.home-assistant.io/integration-template is not working.
