### ISSUE TITLE
Property response_variable is not allowed when calling a script. 

### ISSUE THREAD

**Issue by thejeffreystone** [keesschollaart81/vscode-home-assistant#2765]
Response Variable is being reported as not allowed. I put a pull request in to fix the same error for the stop action in scripts. 
But this is for capturing the return value when the script is called. 

The below config works, but the VSCode reports it as being invalid - > Property response_variable is not allowed.

```YAML
- service: script.get_room_services
   data:
     room: >
        {{who}}
   response_variable: room_services
   - yaml
```

I couldn't figure out where I would fix this one, or I would have sent a pull request....
