### ISSUE TITLE
YAML parsing error for the blueprint config_entry selector

### ISSUE THREAD

**Issue by jlpouffier** [keesschollaart81/vscode-home-assistant#2768]
👋 The blueprint config_entry selector seems to not be recognized as valid by the YAML parser

**YAML Snippet:**
```YAML
blueprint:
  input:
    open_ai_config_entry:
      name: OpenAi Configuration Entry
      description: The OpenAI configuration entry that will be used to generate the image
      selector:
        config_entry:
          integration: "openai_conversation"
```

The blueprint is valid and works.

[Here is the documentation entry of that particular selector](https://www.home-assistant.io/docs/blueprint/selectors/#config-entry-selector)

And here is a picture of what it looks like, today, on VS Code:
![image](https://github.com/keesschollaart81/vscode-home-assistant/assets/5878296/de7ba1e1-18e8-4e3a-859f-080968d9be50)

Thx you very much!
