### ISSUE TITLE
`id` not recognized in the new `conversation` `trigger`

### ISSUE THREAD

**Issue by jlpouffier** [keesschollaart81/vscode-home-assistant#2779]
The property `id` is not recognized when creating a trigger with the new type `conversation` available since the 2023.7

```YAML
trigger:
  - platform: conversation
    command:
    - '{command1} et {command2}'
    id: fr
```
Here is a screenshot of how it looks like today in VSCode
<img width="494" alt="image" src="https://github.com/keesschollaart81/vscode-home-assistant/assets/5878296/559f49de-7102-411b-bd13-ef5cf034057c">

The automation is available [here](https://github.com/jlpouffier/home-assistant-config/blob/master/automations.yaml#L2253-L2299) in case it is needed
