### ISSUE TITLE
`wildcard` not recognised when creating `custom_sentence`

### ISSUE THREAD

**Issue by jlpouffier** [keesschollaart81/vscode-home-assistant#2780]
The new property `wildcard` (available since the 2120.8) is not recognized when creating a `custom_sentence` with a `list`

```YAML
language: "fr"
intents:
  Reminder:
    data:
      - sentences:
          - "Rappelle-moi dans [{days} jour[s]] [et] [{hours} h[eure][s]] [et] [{minutes} min[unte][s]] [et] [{seconds} seconde[s]] (de |d'){reminder}"
          - "Rappelle-moi (de |d'){reminder} dans [{days} jour[s]] [et] [{hours} h[eure][s]] [et] [{minutes} min[unte][s]] [et] [{seconds} seconde[s]]"

lists:
  reminder:
    wildcard: true
  ...

```

Here is how it looks like in VSCode today:
<img width="547" alt="image" src="https://github.com/keesschollaart81/vscode-home-assistant/assets/5878296/4f266183-b6bc-439a-94b2-0f45c6c4aab4">

The custom_sentence is available [here](https://github.com/jlpouffier/home-assistant-config/blob/master/custom_sentences/fr/reminder.yaml) in case it is needed.
