### ISSUE TITLE
Conditional Entity Row

### ISSUE THREAD

**Issue by SeanPM5** [keesschollaart81/vscode-home-assistant#279]
Starting in Home Assistant 0.105 there is support for a conditional entity row inside the Lovelace Entities card (PR https://github.com/home-assistant/frontend/pull/4569 and docs https://www.home-assistant.io/lovelace/entities/#conditional).

Below is a code example from my setup which works and is valid, but throws warnings in the extension.

```YAML
- type: entities
  entities:
    - binary_sensor.sleeping
    - sensor.time_slept_today
    # Only show this below row after I've woken up
    - type: conditional
      conditions:
        - entity: binary_sensor.sleeping
          state: 'off'
      row:
        entity: input_datetime.sean_awake_time
```

Missing property "entity".
Property conditions is not allowed.
Property row is not allowed.
