### ISSUE TITLE
Error using template integration with image configuration variable

### ISSUE THREAD

**Issue by elchininet** [keesschollaart81/vscode-home-assistant#2796]
Using [the template integration with an image configuration variable](https://www.home-assistant.io/integrations/template/#image), everything works as expected in Home Assistant, but VS Code complains about the `image` parameter.

```YAML
template:
  - image:
      - name: Name of the image
        unique_id: id_of_the_image
        url: https://xxx:8123/local/image.png
```

<img width="431" alt="image" src="https://github.com/keesschollaart81/vscode-home-assistant/assets/3728220/ab61efb9-38c7-4111-962d-3ad7ce06bb34">
