### ISSUE TITLE
Incorrect type error when `!include_dir_named` is used in `configuration.yaml`

### ISSUE THREAD

**Issue by ChrisBaker97** [keesschollaart81/vscode-home-assistant#2801]
Parsing `configuration.yaml` produces errors when template entities are included using `!include_dir_named`:

```
Incorrect type. Expected "object".
```

All works fine, and the configuration passes Home Assistant's YAML validation.

Please include the related YAML code:

```YAML
sensor:
  - platform: template
    sensors: !include_dir_named template_sensors/

binary_sensor:
  - platform: template
    sensors: !include_dir_named template_binary_sensors/

switch:
  - platform: template
    switches: !include_dir_named template_switches/
```

A representative file, `template_sensors/illumination.yaml`:
```YAML
friendly_name: "Illumination"
unique_id: sensor.illumination
attribute_templates:
  angle: "{{ state_attr('sun.sun','elevation') | float(0.0) }}"
  effective_angle: "{{ state_attr('sun.sun','elevation')|float(0.0) - states('input_number.sun_angle_bias')|float(0.0) }}"
value_template: >-
  {% set elevation = state_attr('sun.sun','elevation') | float(0.0) %}
  {% if elevation > 0.0 %} Day
  {% elif elevation > -6.0 %} Civil Twilight
  {% elif elevation > -12.0 %} Nautical Twilight
  {% elif elevation > -18.0 %} Astronomical Twilight
  {% else %} Night
  {% endif %}
icon_template: >-
  {% set elevation = state_attr('sun.sun','elevation') | float(0.0) %}
  {% if elevation > 0.0 %} mdi:weather-sunny
  {% elif elevation > -18.0 %} mdi:weather-sunset
  {% else %} mdi:weather-night
  {% endif %}
```

Extension runs in:
- [X] VS Code for Desktop 
- [ ] Hassio Add-on 
- [ ] Visual Studio Online
- [ ] Other: 

I'm running VS Code on:
- [ ] Windows 
- [X] Mac 
- [ ] Linux 

I'm accessing my files:
- [ ] From local disk 
- [ ] Via remote SSH 
- [X] Smb
- [ ] Other:
