### ISSUE TITLE
Property image is not allowed in templates

### ISSUE THREAD

**Issue by revolter** [keesschollaart81/vscode-home-assistant#2813]
Copying this sample:

```yaml
template:
  - trigger:
      alias: "Update image when a new weather image is generated"
      platform: event
      event_type: new_weather_image
    image:
      name: "AI generated image of New York"
      url: "{{ trigger.event.data.url }}"
```

from https://www.home-assistant.io/integrations/openai_conversation/ causes this error to be reported:

![IMG_5060](https://github.com/home-assistant/home-assistant.io/assets/5748627/b3fbd0c6-9ebb-48e4-adb9-1502dd29e2b3)

Source: https://github.com/home-assistant/home-assistant.io/issues/28615
