### ISSUE TITLE
'Property fields/description not allowed ' in script configuration

### ISSUE THREAD

**Issue by neoc83** [keesschollaart81/vscode-home-assistant#284]
The validation comlains about 'Property fields/description not allowed ' in script configuration. See example code and screenshot below. Both the 'fields' and 'description' properties are allowed according to the HA documentation and also passes the validation in HA.

```YAML
blink_light:
  alias: Blink light
  description: Blink the light that is passed as parameter 'light_entity_id'
  fields:
    light_entity_id:
      description: 'The entity_id of the light'
      example: 'light.light_1'
  sequence:
    - service: light.toggle
      data_template:
        entity_id: "{{ light_entity_id }}"
    - delay:
        seconds: 1
    - service: light.toggle
      data_template:
        entity_id: "{{ light_entity_id }}"
```
![image](https://user-images.githubusercontent.com/4459986/76502581-84653380-6444-11ea-8c5f-7ecc8a7469df.png)
