### ISSUE TITLE
Property action ist not allowed in templates

### ISSUE THREAD

**Issue by RealKoenisch** [keesschollaart81/vscode-home-assistant#2884]
configuration.yaml
```
template:
  - trigger:
      - platform: time_pattern
        hours: "/1"
      - platform: homeassistant
        event: start
      - platform: event
        event_type: event_template_reloaded
    action:
      - service: weather.get_forecast
        data:
          type: daily
        target:
          entity_id: weather.eeeeeeeeeee
        response_variable: vorhersage
```
The message "Property action ist not allowed" is shown behind action:
 
Analog to property image is not allowed in templates #2813
