### ISSUE TITLE
Not accept url action under tap_action of entities

### ISSUE THREAD

**Issue by valepe** [keesschollaart81/vscode-home-assistant#296]
After reading 1 & 2 👆, type your issue here and please include the related YAML code like this:

from version 0.100 a new url action is allowed for tap_action, hold_action and double_tap_action options of entities.

```YAML
      - entity: binary_sensor.myentity
        name: Name
        double_tap_action:
          action: url
          url_path: https://www.apple.com
```

and/or point to a repository containing your Home Assistant Configuration
