### ISSUE TITLE
Features for thermostat and humidifier cards are not supported

### ISSUE THREAD

**Issue by definitio** [keesschollaart81/vscode-home-assistant#2979]
```YAML
              - type: thermostat
                entity: climate.thermostat
                name: " "
                features:
                  - type: climate-hvac-modes
                    style: icons
                    hvac_modes:
                      - cool
                      - heat
                      - "off"
                  - type: climate-preset-modes
                    style: icons
                    preset_modes:
                      - away
                      - boost
                      - comfort
```

https://www.home-assistant.io/blog/2023/12/06/release-202312/#new-design-for-the-thermostat-card
