### ISSUE TITLE
Data template dictionary is not supported

### ISSUE THREAD

**Issue by definitio** [keesschollaart81/vscode-home-assistant#2995]
```YAML
    - service: light.turn_on
      entity_id: light.stairs
      data: "{{ {'effect': 'Addressable DDP'} if target else {} }}"
```
![Screenshot_20240102_162525](https://github.com/keesschollaart81/vscode-home-assistant/assets/37266727/da498b73-01bc-405f-9cac-9a6548f366bb)

Error: `Incorrect type. Expected "object".`
The syntax is correct - https://www.home-assistant.io/docs/scripts/service-calls/#use-templates-to-determine-the-attributes
