### ISSUE TITLE
warning "Incorrect type. Expected object." for mqtt - light

### ISSUE THREAD

**Issue by mariowitdoek** [keesschollaart81/vscode-home-assistant#2996]
I have the same warning as in https://community.home-assistant.io/t/mqtt-sensor-incorrect-type-error/601533

mqtt:
  - light:
      name: "Licht bureau"
      unique_id: qbus_l_bureau

Checking from withing HA it is all OK.
It is HA Container based (with docker) configuration.

I really like the tool ... hopefully this bug wan be fixed. 
I will also look into it but this is all new for me.

Mario

**Comment by frenck** [comment]
That syntax is incorrect:

```
mqtt:
  light:
    - name: "Licht bureau"
      unique_id: qbus_l_bureau
      command_topic: ...
```

../Frenck
