### ISSUE TITLE
Automations lists are broken after v1.40.0

### ISSUE THREAD

**Issue by definitio** [keesschollaart81/vscode-home-assistant#3021]
All my automations are included via `!include_dir_merge_list`. With v1.40.0 there are errors in every file with automations:

```YAML
- alias: create_groups
  id: 5b3f20ca-3edf-4fd6-a1d8-98561a5f9449
  initial_state: true
  mode: single
  trigger:
    - platform: homeassistant
      event: start
    - platform: event
      event_type: platform_discovered
  action:
    - parallel:
        - service: group.set
          data:
            object_id: all_water_leak_sensors
            name: Датчики протечки
            entities: >-
              {% from 'group.jinja' import get_entities %}
              {{ get_entities('moisture', 'all_water_leak_sensors') }}

        - service: group.set
          data:
            object_id: all_windows
            name: Окна
            entities: >-
              {% from 'group.jinja' import get_entities %}
              {{ get_entities('window', 'all_windows') }}

- alias: kodi_power
  id: ffa6e561-99c6-4ae1-84c3-e6e4f91ddfae
  initial_state: true
  mode: parallel
  trigger:
    - platform: event
      event_type:
        - kodi.turn_on
        - kodi.turn_off
  action:
    - if: "{{ trigger.event.event_type == 'kodi.turn_on' }}"
      then:
        - if: "{{ trigger.event.data.entity_id == 'media_player.lroom_stb' }}"
          then:
            - service: button.press
              entity_id: button.lroom_aquarium_stb_power
      else:
        - service: kodi.call_method
          data:
            entity_id: "{{ trigger.event.data.entity_id }}"
            method: System.Shutdown
```
![Screenshot_20240113_151835](https://github.com/keesschollaart81/vscode-home-assistant/assets/37266727/50fb42b5-2e0a-4f72-96e0-fdc7a3538088)

```
Missing property "panels".
Missing property "platform".
Property alias is not allowed.
Property id is not allowed.
Property initial_state is not allowed.
Property mode is not allowed.
Property trigger is not allowed.
Property action is not allowed.
```
