### ISSUE TITLE
Autocompletion not working when typing in an !include file

### ISSUE THREAD

**Issue by baudneo** [keesschollaart81/vscode-home-assistant#3086]
# Problem/Motivation

So, maybe I am missing a setting but, I cant get auto complete of entities to work when I am editing a file that has been `!include`'d from `configuration.yaml`. If I move the file contents out of the `!include` file and put it in its configuration section in `configuration.yaml`, the entities get autocompleted.

Is there a way to get the `!include` file autocomplete working? The Home Assistant Config Helper extension says it is enabled globally.

## Expected behaviour

Autocompletion of entity values in the file defined in `!include`

## Actual behaviour

No autocompletion of entities

##### configuration.yaml

```yaml
emulated_hue: !include emulated_hue.yaml
```

##### emulated_hue.yaml
```yaml
type: alexa
host_ip: 10.0.1.20
listen_port: 80
expose_by_default: false
entities:
  light.overhead:
    name: "Room overhead"
    hidden: false
```
I can't get autocomplete to work when typing `light.`

##### configuration.yaml
```yaml
emulated_hue:
  type: alexa
  host_ip: 10.0.1.20
  listen_port: 80
  expose_by_default: false
  entities:
    light.overhead:
      name: "Room overhead"
      hidden: false
```
I get autocompletion when typing `light.`

## Proposed changes

> (If you have a proposed change, workaround or fix,
> describe the rationale behind it)
