### ISSUE TITLE
[Bug] Schema Validation: Property conversation_agent is not allowed (Selectors)

### ISSUE THREAD

**Issue by droans** [keesschollaart81/vscode-home-assistant#3108]
Add-in reports the error "Property conversation_agent is not allowed" as a selector. The validator needs to be updated with the most recent schema.

[Documentation](https://www.home-assistant.io/docs/blueprint/selectors/#conversation-agent-selector)

[Affected File](https://github.com/keesschollaart81/vscode-home-assistant/blob/dev/src/language-service/src/schemas/integrations/selectors.ts)

Example Code:

```
blueprint:
  input:
    conversation_agent_selector:
      selector:
        conversation_agent: {}
   ...
```
