### ISSUE TITLE
Schema Validation: Text Selector: Property Multiple is not allowed (Selectors)

### ISSUE THREAD

**Issue by droans** [keesschollaart81/vscode-home-assistant#3109]
Add-in reports the error "Property multiple is not allowed" for the text selector. The validator needs to be updated with the most recent schema.

[Documentation](https://www.home-assistant.io/docs/blueprint/selectors/#multiple)

[Affected File](https://github.com/keesschollaart81/vscode-home-assistant/blob/dev/src/language-service/src/schemas/integrations/selectors.ts)

Example Code:

```
blueprint:
  input:
    text_selector:
      selector:
        text:
          multiple: true
   ...
```
