### ISSUE TITLE
KNX sensor schema incomplete

### ISSUE THREAD

**Issue by ehn** [keesschollaart81/vscode-home-assistant#3134]
The following snippet from `configuration.yaml`:

```YAML
knx:
  sensor:
    - name: Hot tub water temperature out
      state_address: '5/1/6'
      sync_state: 2
      type: temperature
```

generates a schema error. The validator doesn't like the bare `2`. However, according to the [KNX integration documentation](https://www.home-assistant.io/integrations/knx/#sync_state), it looks like it's a shorthand for `expire 2` and valid.
