### ISSUE TITLE
Property alias is not allowed for sequence

### ISSUE THREAD

**Issue by dannytsang** [keesschollaart81/vscode-home-assistant#3138]
Adding an alias to a squence gives the following error:
![image](https://github.com/user-attachments/assets/955cd75a-747b-4dfc-9913-54b4c2767f95)

The automation was generated from the UI so I believe this is allowed. As soon as I remove the alias line, the error goes away.

```YAML
  - id: "1724096560132"
    alias: "Office: Pre-cool"
    description: ""
    trigger:
      - platform: time
        at: 07:00:00
    condition:
      - condition: state
        entity_id: input_boolean.enable_office_air_conditioner_automations
        state: "on"
      - condition: state
        entity_id: binary_sensor.workday_sensor
        state: "on"
    action:
      - parallel:
          - service: script.send_direct_notification
            data:
              message: pre cooling
              title: office
              people:
                entity_id: person.danny
          - alias: Set Air conditioner unit
            sequence:
              - action: climate.set_hvac_mode
                metadata: {}
                data:
                  hvac_mode: cool
                target:
                  entity_id: climate.office_air_conditioner
              - delay:
                  hours: 0
                  minutes: 0
                  seconds: 2
                  milliseconds: 0
              - action: climate.set_temperature
                metadata: {}
                data:
                  temperature: 18
                target:
                  entity_id: climate.office_air_conditioner
    mode: single
```
