### ISSUE TITLE
tap_action errors

### ISSUE THREAD

**Issue by definitio** [keesschollaart81/vscode-home-assistant#3220]
```YAML
                    tap_action:
                      action: perform-action
                      data:
                        entity_id: *pc_turn_off_screen_entity
                      perform_action: button.press
```

![Screenshot_20241006_112909](https://github.com/user-attachments/assets/342952b4-c807-4242-a1ec-37354849419f)
Errors:

```
Missing property "service".
Value must be "call-service".
Property perform_action is not allowed.
```

https://www.home-assistant.io/dashboards/actions/
