### ISSUE TITLE
String does not match the pattern of "LEGACY_SYNTAX^"

### ISSUE THREAD

**Issue by baudneo** [keesschollaart81/vscode-home-assistant#3241]
I am seeing this error in some of the files I have `!include` / `!include_dir_named` in configuration.yaml:

`String does not match the pattern of "LEGACY_SYNTAX^".yaml-schema: http://schemas.home-assistant.io/integration-homeassistant-packages`

### configuration.yaml
```yaml
homeassistant:
  packages: !include_dir_named packages

script: !include scripts.yaml
```

### packages/[file].yaml
```YAML
automation:
  - id: unavailable_entities_notification
    alias: "Unavailable Entities Notification"
    description: "Create persistent notification if unavailable entities, dismiss if none."
    mode: restart
    trigger:
      - platform: state
        entity_id: sensor.unavailable_entities
        attribute: entity_id
        to: ~
    condition:
      - condition: template
        alias: "Sensor state is a valid numerical value"
        value_template: >
          {{ is_number(trigger.from_state.state)
              and is_number(trigger.to_state.state) }}
    action:
      - if:
          - condition: numeric_state
            entity_id: sensor.unavailable_entities
            below: 1
        then:
          - service: persistent_notification.dismiss
            data:
              notification_id: unavailable_entities
        else:
          - service: persistent_notification.create
            data:
              notification_id: unavailable_entities
              title: "Unavailable Entities"
              message: "{{ state_attr('sensor.unavailable_entities', 'entity_id') | join('\n') }}"
```
![2024-10-15_20-07](https://github.com/user-attachments/assets/7060fc68-f3ab-4619-9ff2-d98cbb8b1054)

### scripts.yaml
```yaml
tts_save_dot_volume:
  alias: Save Current Volume for Ecobee TTS
  sequence:
    - service: var.set
      data:
        entity_id: var.tts_ecobee_dot_volume
        value_template: "{{ state_attr('media_player.tyler_s_ecobee_smartthermostat_with_voice_control', 'volume_level') }}"

tts_restore_dot_volume:
  alias: Restore Previous Volume for Ecobee TTS
  sequence:
    - service: media_player.volume_set
      data:
        entity_id: media_player.tyler_s_ecobee_smartthermostat_with_voice_control
        volume_level: >
          {% if states('var.tts_ecobee_dot_volume') != 'None' %}
            {{ states('var.tts_ecobee_dot_volume') | float }}
          {% else %}
            .5
          {% endif %}

livingroom_cam_mode:
  sequence:
    - service: shell_command.zm_get_mon_func
      data:
        mid: 14
      response_variable: mon_func
livingroom_cam_off:
  sequence:
    - service: shell_command.zm_change_camera_function
      data:
        mid: 14
        state: none
```
![2024-10-15_20-16](https://github.com/user-attachments/assets/e1ae1b8a-ec6d-43b1-9171-6ac8df175a6d)
