### ISSUE TITLE
Warnings in scripts for description, icon and fields

### ISSUE THREAD

**Issue by fribse** [keesschollaart81/vscode-home-assistant#326]
```YAML
send_rf_command:
  alias: Send RF command sequence
  icon: "mdi:radio-tower"
  description: Sends a series of settings to the sonoff RF Bridge to set star-light
  fields:
    RfSync:
      description: RfSync value from rfbridge
      example: '12200'
    RfLow:
      description: RfLow value from rfbridge
      example: '430'
    RfHigh:
      description: RfHigh value from rfbridge
      example: '1250'
    RfCode:
      description: 'RfCode value from rfbridge, must start with #'
      example: '#D10601'
  sequence:
  - service: mqtt.publish
    data_template:
      topic: cmnd/rfbridge/RfSync
      payload: '{{ RfSync }}'
  - service: mqtt.publish
    data_template:
      topic: cmnd/rfbridge/RfLow
      payload: '{{ RfLow }}'
  - service: mqtt.publish
    data_template:
      topic: cmnd/rfbridge/RfHigh
      payload: '{{ RfHigh }}'
  - service: mqtt.publish
    data_template:
      topic: cmnd/rfbridge/RfCode
      payload: '{{ RfCode }}'
```
It shows this error:
![image](https://user-images.githubusercontent.com/13660621/81731273-fe3e8b00-948e-11ea-900e-0624458ed2d4.png)
As far as I can see that is allowed to use in scripts.
