### ISSUE TITLE
knx device_class value volatile_organic_compounds_parts shown as "not accepted"

### ISSUE THREAD

**Issue by wk2001** [keesschollaart81/vscode-home-assistant#3282]
Here my yaml extract:

```YAML
knx:
  sensor:
    - name: "VOC Bad 1. OG"
      state_address: "5/1/102"
      type: ppm
      sync_state: true
      state_class: measurement
      device_class: volatile_organic_compounds_parts
```

For `device_class` I get the error/warning in the Studio Code Server add on in Home Assistant:

> Value is not accepted. Valid values: "apparent_power", "aqi", "atmospheric_pressure", "battery", "carbon_dioxide", "carbon_monoxide", "current", "data_rate", "data_size", "date", "distance", "duration", "energy", "energy_storage", "enum", "frequency", "gas", "humidity", "illuminance", "irradiance", "moisture", "monetary", "nitrogen_dioxide", "nitrogen_monoxide", "nitrous_oxide", "ozone", "pm1", "pm10", "pm25", "power", "power_factor", "precipitation", "precipitation_intensity", "pressure", "reactive_power", "signal_strength", "sound_pressure", "sulphur_dioxide", "temperature", "timestamp", "volatile_organic_compounds", "voltage", "volume", "volume_storage", "water", "weight", "wind_speed".yaml-schema: http://schemas.home-assistant.io/integration-homeassistant-packages(1)

Following https://www.home-assistant.io/integrations/knx#device_class `volatile_organic_compounds_parts` is a valid value and there are no issues in Home Assistant itself.
