### ISSUE TITLE
Add an id and unique-id generator

### ISSUE THREAD

**Issue by schmittyd** [keesschollaart81/vscode-home-assistant#3294]
Hi,

It would be good if a generator could be implemented to generate random 13 digit numbers for Automation ids and unique-ids of 8-4-4-4-12 random alphanumeric characters.

Examples:

```yaml
automation:
  - id: '0123456789012'
```
```yaml
light:
  - platform: group
    unique_id: 0a1b2c3d-4e5f-6g7h-8i9j-0k1l2m3n4o5p
```
