### ISSUE TITLE
Schema not aware of new automation trigger "knx.telegram"

### ISSUE THREAD

**Issue by shurli** [keesschollaart81/vscode-home-assistant#3299]
from the docs:
[https://www.home-assistant.io/integrations/knx/#triggers](https://www.home-assistant.io/integrations/knx/#triggers)

```YAML
- alias: "Single group address trigger"
  triggers:
    - trigger: knx.telegram
      destination: 1/2/3
      group_value_read: false
      outgoing: false
  conditions: "{{ trigger.value == 0 }}"
  actions: []
```
