### ISSUE TITLE
Yaml error on MQTT fan command_template

### ISSUE THREAD

**Issue by jbperrin88** [keesschollaart81/vscode-home-assistant#3311]
Hi there,

First off all , thanks for this amazing piece of software . 

I'm trying to create mqtt fan device / entity but i've an yaml error on 'command_template'

![image](https://github.com/user-attachments/assets/54cda356-1a79-4af1-93f3-9c13cf5386de)

I can't use 'payload_on' and 'payload_off' cause my mqtt except a json. So i really need to use template.

```yaml
mqtt:
  fan:
    - name: "Ventilateur Hall"
      device:
        name:  "Ventilateur Hall"
        manufacturer: delta PLC
        identifiers: delta_plc_fan_hall
      unique_id: delta_plc_fan_hall
      state_topic: "hnb/plc/fan/status/all"
      state_value_template: >
        {{ iif( value_json.d.state[0] == 0, 'off' , 'on' ) }}
      command_topic: "none"
      command_topic: "hnb/plc/fan/on_off/all"
      command_template: ""
```

![image](https://github.com/user-attachments/assets/f675fbce-22b4-4bb5-be5b-04d9b05b7114)

Can you please update the schemas ? 

I've read this closed issue: https://github.com/keesschollaart81/vscode-home-assistant/issues/2987
I've the same behaviour and I don't really understand the documentation to update the schema by myself .

Best regards
