### ISSUE TITLE
Syntax error when no property "topic" is provided

### ISSUE THREAD

**Issue by Frantik85** [keesschollaart81/vscode-home-assistant#3331]
The error occures in this line: "- platform: template" with the message "Missing property 'topic'".

I'd like to state, that I'll be happy to fix it, if this is actually a valid false-positive. After searching, I could not find a hint on why to add this there.

```YAML
heizung_co2_schwellwertberechnung:
  alias: Heizung - CO2-Schwellwertberechnung
  sequence:
  - wait_for_trigger:
    - platform: template
      value_template: '{{(states(''sensor.co2_wohnzimmer'')| float >= states(''input_number.heizung_co2_oberer_schwellwert'')|float)
        or

        (states(''sensor.co2_wohnzimmer'')| float <= states(''input_number.heizung_co2_unterer_schwellwert'')|float)}}'
  - choose:
    - conditions:
      - condition: template
        value_template: '{{(states(''sensor.co2_wohnzimmer'')| float >= states(''input_number.heizung_co2_oberer_schwellwert'')|float)}}'
      sequence:
      - action: input_boolean.turn_on
        target:
          entity_id: input_boolean.heizung_co2_grenzwertstatus_mit_hysterese
        data: {}
    - conditions:
      - condition: template
        value_template: '{{(states(''sensor.co2_wohnzimmer'')| float <= states(''input_number.heizung_co2_unterer_schwellwert'')|float)}}'
      sequence:
      - action: input_boolean.turn_off
        target:
          entity_id: input_boolean.heizung_co2_grenzwertstatus_mit_hysterese
        data: {}
  description: Berechnet den Status für input_boolean.heizung_co2_grenzwertstatus_mit_hysterese
  icon: mdi:molecule-co2
```

BR,
Daniel
