### ISSUE TITLE
repeat for_each "Incorrect type. Expected "string"."

### ISSUE THREAD

**Issue by derjoerg** [keesschollaart81/vscode-home-assistant#3344]
![vscode_incorrect-type-string](https://github.com/user-attachments/assets/716f2214-9ff9-4032-9d7b-226c6a8e4023)

```YAML
- id: sun_protection
  alias: 16 Sonnenschutz
  description: ''
  trigger:
  - trigger: state
    entity_id:
    - input_button.sonnenschutz
  condition: []
  action:
  - repeat:
      for_each:
      - window: binary_sensor.raum_1_rechts_raum_1
        cover: cover.zimmer_1_rechts
        message: im Gästezimmer
        position: 0
      - window: binary_sensor.raum_1_links_raum_1
        cover: cover.zimmer_1_links
        message: im Gästezimmer
        position: 0
      - window: binary_sensor.kuche_kuche
        cover: cover.kuche
        message: in der Küche oben
        position: 0
      - window: binary_sensor.raum_2_links_raum_2
        cover: cover.zimmer_2
        message: im Nähzimmer
        position: 0
      - window: binary_sensor.bad_bad_2
        cover: cover.bad
        message: im Bad oben
        position: 25
      sequence:
      - if:
        - condition: template
          value_template: '{{ is_state(repeat.item.window, ''off'') }}'
```

It is also shown like this in the documentation https://www.home-assistant.io/docs/scripts/#for-each
