### ISSUE TITLE
Incorrect flag for valid use of 'not' condition

### ISSUE THREAD

**Issue by grantalewis** [keesschollaart81/vscode-home-assistant#340]
```YAML
  - alias: Trigger Son Asleep When No Alarm Set
    initial_state: 'on'
    trigger:
      - platform: time_pattern
        minutes: '/5'
        seconds: 00
    condition:
      condition: and
      conditions:
        - condition: template
          value_template: >
            {{ is_state('light.son_bedroom_son_bedroom_fan_light','off') and is_state('light.son_bedroom_son_bedroom_fan','on') }}
        - condition: state
          entity_id: input_boolean.son_awake
          state: 'on'
        - condition: not
          conditions:
            - condition: time
              after: '07:00:00'
            - condition: time
              before: '22:00:00'
    action:
      - service: input_boolean.turn_off
        entity_id: input_boolean.son_awake
```
<img width="806" alt="Screen Shot 2020-05-23 at 8 31 46 AM" src="https://user-images.githubusercontent.com/9505044/82731326-fd4dfa80-9cd3-11ea-8d29-1d8dc9008ea5.png">
