### ISSUE TITLE
Cannot find the files in folder dev/fd

### ISSUE THREAD

**Issue by megapearl** [keesschollaart81/vscode-home-assistant#3446]
Please include the related YAML code:

```YAML
{
  "git.enableSmartCommit": true,
  "git.confirmSync": false,
  "workbench.colorTheme": "Default Dark Modern",
  "window.menuBarVisibility": "classic",
  "github.gitProtocol": "ssh",
  "git.autofetch": true,
  "remote.autoForwardPortsSource": "hybrid",
  "codeium.detectProxy": false,
  "window.confirmBeforeClose": "never",
  "html.format.contentUnformatted": "",
  "vscode-home-assistant.longLivedAccessToken": "REDACTED",
  "vscode-home-assistant.hostUrl": "HTTPS URL via HAPROXY reverse proxy here.",
  "[home-assistant]": {
    
    "editor.insertSpaces": true,
    "editor.tabSize": 2,
    "editor.quickSuggestions": {
      "other": true,
      "comments": false,
      "strings": true
    },
    "editor.autoIndent": "advanced"
  }
}
```

Find my Home Assistant Configuration here:
[Link to Home Assistant Configuration](<link to repo here>)

Extension runs in:
- [ ] VS Code for Desktop 
- [ ] Hassio Add-on 
- [ ] Visual Studio Online
- [X] Other: Code-Server Docker

I'm running VS Code on:
- [ ] Windows 
- [ ] Mac 
- [X] Linux 

I'm accessing my files:
- [ ] From local disk 
- [ ] Via remote SSH 
- [ ] Smb
- [X] Other: docker mount points

I'm running the code-server standalone and created a 'dashboard' webpage to it in home assistant, which opens code-server in the right directory where the homeassistant configuration lives.

Errors in debug log:
[Home Assistant Language Server(6974)] Started and initialize received
Cannot find the files in folder dev/fd

I tried different versions of vs-code-homeassistant, v1.39 is also not working.
Howto debug?
