### ISSUE TITLE
Property hw_version  is not allowed.

### ISSUE THREAD

**Issue by CoolJoe72** [keesschollaart81/vscode-home-assistant#3529]
Missing device property _'hw_version'_ in configuration.yaml for a mqtt > sensor > device 

``` yaml
mqtt:
  sensor:
    - name: "Gas Meter"
      state_topic: "******"
      device_class: gas
      state_class: total_increasing
      unique_id: gas_##########
      unit_of_measurement: "ft³"
      icon: mdi:meter-gas
      device:
        identifiers: "##########"
        manufacturer: "Itron"
        model: "Elster American AC250"
        hw_version: "100G DLS"
        name: "Home Gas"
```

![Image](https://github.com/user-attachments/assets/67771488-bc2a-4b71-9b6d-8d80817430b8)
