### ISSUE TITLE
action - scene in automations / scan_intervall for mqtt-sensor

### ISSUE THREAD

**Issue by pschneider87** [keesschollaart81/vscode-home-assistant#360]
```YAML
alias: xxxx
  description: ''
  trigger:
  - device_id: xxxxxxx
    domain: binary_sensor
    entity_id: binary_sensor.hue_motionsensor_flur
    for:
      hours: 0
      minutes: 1
      seconds: 0
    platform: device
    type: no_motion
  condition: []
  action:
  - scene: scene.flur_licht_aus
```
It's parsing an error for "- scene" but it's working in HA.

```YAML
sensor:
  - platform: mqtt
    state_topic: "valetudo/alfred/state"
    json_attributes_topic: "valetudo/alfred/map_data_parsed"
    name: alfred_map
    value_template: 'OK'
    scan_interval: 5
```
It's parsing an error for "- scan_intervall", but it's working in HA.

I would change it by myself, but I do not completely understand the ts-files.
