### ISSUE TITLE
"Unresolved tag: !secret" whilst definition does work

### ISSUE THREAD

**Issue by hmmbob** [keesschollaart81/vscode-home-assistant#3609]
![Image](https://github.com/user-attachments/assets/6b0b704f-63c7-4424-8e0c-3d432d02e209)

"Go to definition" works for all of them.

```YAML
sonos:
  media_player:
    advertise_addr: !secret sonos_host

notify:
  - platform: smtp
    name: "Email"
    sender: !secret smtp_sender
    sender_name: "Homeassistant"
    username: !secret smtp_sender
    password: !secret smtp_sender_password
    recipient: !secret smtp_recipient
    server: !secret smtp_server
    port: !secret smtp_server_port
    encryption: tls
```
