### ISSUE TITLE
"Action <entity> does not exist in your Home Assistant instance" but not in action context

### ISSUE THREAD

**Issue by paulbusse** [keesschollaart81/vscode-home-assistant#3623]
VS Code complains about this piece of YAML

```YAML
  id: a2352422dd634878a54720e85d533b42
  alias: turning on sitting room ligths  trigger:
  - trigger: state
    entity_id:
    - light.lichten_salon
    from: 'off'
    to: 'on'
  action:
  - action: script.turn_on
    data: {}
    target:
      entity_id: script.activate_sitting_room_scene
```
Here is the complaint
```
[{
	"resource": "/home/paul/homeserv_homeassistant/homeassistant/automations.yaml",
	"owner": "_generated_diagnostic_collection_name_#0",
	"code": "unknown-action",
	"severity": 4,
	"message": "Action 'light.lichten_salon' does not exist in your Home Assistant instance",
	"source": "home-assistant",
	"startLineNumber": 81,
	"startColumn": 7,
	"endLineNumber": 81,
	"endColumn": 26
}]
```
The entity light.lichten_salon exists.

I get the same error for every trigger based directly on an entity. I.e. not for the templates.

And btw. Thanks for the extension.
