### ISSUE TITLE
Connection errors and syntax errors

### ISSUE THREAD

**Issue by yelkenli1** [keesschollaart81/vscode-home-assistant#3644]
The attached image is the problem I am most concerned about. If you have any insight, please let me know. 

Another issue, most likely unrelated has to do with syntax errors. 
Months ago, I was getting multiple syntax errors, but that seems to have gone away. I made no changes. I do have auto update enabled. 
The below is associated with !secret and flags in both the config file and an automation file in an automation folder. In this snippet, I get Unresolved tag !secret yaml for the lines that have !secret...
```YAML
- alias: scene_living_bright
  trigger:
  - platform: state
    entity_id: switch.hall_scene_controller
    to: 'on'
  action:
    - service: light.turn_on
      data:
        entity_id: light.living_east
        brightness_pct: !secret LivingEast_high
        transition: 5
    - service: light.turn_on
      data:
        entity_id: light.living_west
        brightness_pct: !secret LivingWest_high
        transition: 5
   - yaml
```

I also get an Unresolved tag error with the !include_dir_merge_list line. 

automation manual: !include_dir_merge_list automations/       # Non UI automations
automation ui: !include automations.yaml                      # Automations I create in the UI

The automations work.

![Image](https://github.com/user-attachments/assets/88e4171b-54ad-45c8-a115-638582282002)
