### ISSUE TITLE
Entity ids are warned as "do not exist" while they do exist

### ISSUE THREAD

**Issue by Kolia56** [keesschollaart81/vscode-home-assistant#3674]
Since v2 version, there are many false positive warnings for "entity_id that do no exist in HA" while they do exist. Auto completion do work for those entity ids

Examples

``` yaml
    action:
      - service: utility_meter.reset
        data: {}
        target:
          entity_id:  
            - select.water_meter_arrosage
```
```yaml
  - alias: Chauffage PID interactions entre les thermostats et les éléments d'interface 
    id: 146eb2fd-3438-4cc2-9605-b41cd733034f
    description: ""
    trace:
      stored_traces: 10
    triggers:
      - trigger: state
        id: consigne_change
        entity_id:
          - input_number.pid_id3_temperature_set
          - input_number.pid_id4_temperature_set
          - input_number.pid_id5_temperature_set
          - input_number.pid_id6_temperature_set
          - input_number.nsp_id21_temperature_set
```
Moreover, in commented code there are entity ids that indeed do not exist anymore, however I think that this check should be disabled in commented code that I keep for further reference.

Thanks a lot for this valuable extension.
