### ISSUE TITLE
Allow the "icon-height" property for the "entity-button" Lovelace card

### ISSUE THREAD

**Issue by DominikPalo** [keesschollaart81/vscode-home-assistant#37]
The `entity-button` Lovelace card supports setting the height of the assigned icon using the `icon-height` property, but the current scheme (v0.6.0) doesn't allow this property.

![image](https://user-images.githubusercontent.com/1623257/57974971-44b6f200-79c1-11e9-9686-7f908739031d.png)

Example:
```
      - type: entity-button
        icon_height: 100px
        tap_action:
          action: toggle
        name: Všetky svetlá v byte
        entity: group.all_lights
        hold_action:
          action: more-info
```
