### ISSUE TITLE
Warning about the v.112 multiple entities condition

### ISSUE THREAD

**Issue by febalci** [keesschollaart81/vscode-home-assistant#371]
On HA v.112, the new structure which allows to use multiple entities and states in YAML configurations causes a warning/error:

```YAML
  condition:
    - condition: state
      entity_id: 
        - binary_sensor.xiaomi_motion_sensor_a
        - binary_sensor.xiaomi_motion_sensor_b
      state: 'off'
```
On "state: 'off'" line it gives:
-> Incorrect type. Expected "string"
