### ISSUE TITLE
Conditional Entity in Picture Elements Card

### ISSUE THREAD

**Issue by holdestmade** [keesschollaart81/vscode-home-assistant#39]
Entity "binary_sensor.openclose_9" is being highlighted - "Incorrect Type. Expected "object".

Works OK in HA.

Example:
```
type: picture-elements
image: /local/images/ground_floor_plan.png
elements:
  - type: conditional
    conditions:
      - entity: binary_sensor.openclose_9
        state: 'on'
    elements:
      - type: image
        image: /local/images/ground_floor_plan_open-patio-doors.png
        style:
          top: 5.7%
          left: 50.17%
          width: 16.15%
```
