### ISSUE TITLE
!include_dir_list is not correctly parsed for automations. 

### ISSUE THREAD

**Issue by bavo** [keesschollaart81/vscode-home-assistant#395]
The plugin creates errors for each of my automations listed in the `!include_dir_list folder. `

It looks like the plugin can only handle `!include_dir_list_merged` types of configuration.

Example:

#### **`automation.yaml`**
``` yaml
automation: !include_dir_list automations/
```

#### **`automations/bureau/lamp-aan.yaml`**
``` yaml
alias: "Bureau: Bureau lamp aan"
trigger:
  - platform: event
    event_type: deconz_event
    event_data: 
      id: schakelaar_bureau
      event: 1000
action:
  service: light.turn_on
  data:
    entity_id: light.bureau 
```

#### **`VsCode example`**
<img width="523" alt="image" src="https://user-images.githubusercontent.com/1813273/87684190-3e1d3980-c782-11ea-8bc2-cbf27fbfc99c.png">
