### ISSUE TITLE
!secret and !include_dir_named throw unknown tag error

### ISSUE THREAD

**Issue by mike240se** [keesschollaart81/vscode-home-assistant#398]
Upgraded to 1.7.2 and still getting this error.  Using vscode server docker (code-server)

Everything else including auto completion seems to work fine.

```YAML
homeassistant:
          packages: !include_dir_named packages

bmw_connected_drive:
  name:
    username: !secret BMW_USER
    password: !secret BMW_PASS
    region: "north_america"

```

Screenshot: https://i.imgur.com/HFocIDD.png
![HFocIDD](https://user-images.githubusercontent.com/31720459/87860470-afd4bf00-c90b-11ea-9e3e-5e6ff24da92f.png)
