### ISSUE TITLE
Missing property "condition"

### ISSUE THREAD

**Issue by philbowers** [keesschollaart81/vscode-home-assistant#399]
It might just be something I haven't configured correctly yet. I just installed the VScode add-on in home assistant and, when looking through file tree, I had 4 error notifications pop-up in one of the files. 

Here's the issue I'm having: When the script states `- domain: switch` VScode throws error `Missing property "condition"`

```
script:
  pool_pump_on:
    alias: pool pump on
    sequence:
    - condition: state
      entity_id: binary_sensor.pool_pump_running
      state: 'off'
    - domain: switch 
      device_id: 59e8cf3f7b5c4d618bad2e57fd180af4
      entity_id: switch.zooz_z16_a000_id_a00a_switch_4
      type: turn_on

  pool_pump_off:
    alias: pool pump off
    sequence:
    - domain: switch 
      device_id: 5ac98b055646498cb818bb10042a8598
      entity_id: switch.zooz_z16_a000_id_a00a_switch_2
      type: turn_off
    - delay: "00:00:10"
    - domain: switch 
      device_id: 59e8cf3f7b5c4d618bad2e57fd180af4
      entity_id: switch.zooz_z16_a000_id_a00a_switch_4
      type: turn_off
    - service: notify.mobile_app_phils_note_10
      data:
        message: The pool pump is off

  polaris_pump_on:  
    alias: polaris pump on
    sequence:
    - condition: state
      entity_id: binary_sensor.pool_pump_running
      state: 'on'
    - condition: state
      entity_id: binary_sensor.polaris_pump_running
      state: 'off'
    - domain: switch 
      device_id: 5ac98b055646498cb818bb10042a8598
      entity_id: switch.zooz_z16_a000_id_a00a_switch_2
      type: turn_on
    - service: notify.mobile_app_phils_note_10
      data:
        message: Polaris pump is on
```
screen capture:
![miss_prop](https://user-images.githubusercontent.com/8340735/87866254-6c02a980-c94d-11ea-8d25-69c37000a846.png)

Visual Studio Code
Current version: 2.3.0

code-server: v3.4.0
 VS Code: v1.45.1
Commit: 69ad52907e8ea109345831d29da5425cb2a55047
Date: 2020-05-27T23:38:22Z
