### ISSUE TITLE
Property allowlist_external_dirs is not allowed.

### ISSUE THREAD

**Issue by Veldkornet** [keesschollaart81/vscode-home-assistant#406]
In 0.113, the `whitelist_external_dirs` changed to `allowlist_external_dirs`, and now the plugin gives the warning that `Property allowlist_external_dirs is not allowed.`

```YAML
homeassistant:
  allowlist_external_dirs:
    - /tmp
```
