### ISSUE TITLE
Choose and default property not allowed

### ISSUE THREAD

**Issue by Pirol62** [keesschollaart81/vscode-home-assistant#438]
After reading 1 & 2 👆, type your issue here and please include the related YAML code like this:

```YAML
action:
    - choose:
        - conditions:
            - condition: template
              value_template: "{{ trigger.to_state.entity_id == person.yvonne }}"
          sequence:
            - service: automation.turn_on
              entity_id: automation.yvonne_begruessung
        - conditions:
            - condition: template
              value_template: "{{ trigger.to_state.entity_id == person.jorg }}"
          sequence:
            - service: automation.turn_on
              entity_id: automation.joerg_begruessung
      default:
        - service: script.turn_on
          entity_id: script.personcounter_check
```
I got the following issues:
![image](https://user-images.githubusercontent.com/48820003/88656145-22922700-d0d0-11ea-80ce-ab99826fa299.png)

The configuration checker allows this and the automation is working
