### ISSUE TITLE
"Incorrect type. Expected integer." after state trigger: for: minutes: {{ template }}

### ISSUE THREAD

**Issue by tomlut** [keesschollaart81/vscode-home-assistant#440]
After reading 1 & 2 👆, type your issue here and please include the related YAML code like this:

```YAML
  trigger:
  - platform: template
    value_template: "{{ states('sensor.cpu_temperature')|float >= states('input_number.rack_fan_on_temp')|int }}"
    for:
      minutes: "{{ states('input_number.rack_fan_dwell_time')|int }}"
```

HA scheme error: "Incorrect type. Expected integer." after the `minutes:` key.

I had a look at the "fix the scheme yourself" link but could not find triggers.
