### ISSUE TITLE
Person entity in zone trigger

### ISSUE THREAD

**Issue by WildRat** [keesschollaart81/vscode-home-assistant#450]
This plugin raises error "String does not match the pattern of "^device_tracker\.(?!_)[\da-z_]+(?<!_)\s?(?:,\s?device_tracker\.(?!_)[\da-z_]+(?<!_))*$"." on zone trigger in autamations with "entity_id: person.somone".

```YAML
trigger:
- entity_id: person.somone
  event: enter
  platform: zone
  zone: zone.home
```
