### ISSUE TITLE
Packages configuration not accepted - Expected "array'

### ISSUE THREAD

**Issue by mirekmal** [keesschollaart81/vscode-home-assistant#456]
After reading 1 & 2 👆, type your issue here and please include the related YAML code like this:

```YAML
homeassistant:
  packages:
    vacuum: !include vacuum.yaml
    weather: !include weather.yaml
    draytek: !include draytek.yaml
    garbage: !include garbage.yaml
    download: !include download.yaml
    scounters: !include scounters.yaml
```

Above code causes VScode to report error: ```Incorrect type. Expected "array". [3,5]```:
```
{
	"resource": "/Volumes/config/configuration.yaml",
	"owner": "_generated_diagnostic_collection_name_#0",
	"severity": 8,
	"message": "Incorrect type. Expected \"array\".",
	"startLineNumber": 3,
	"startColumn": 5,
	"endLineNumber": 8,
	"endColumn": 39
}
```
Changing order/removing/adding lines always causing to point to the first line in packages section. HA config check passes flawlesly.
