### ISSUE TITLE
Wrong errors

### ISSUE THREAD

**Issue by Appyx** [keesschollaart81/vscode-home-assistant#47]
The following code snippets produces the wrong error: `Missing property "event_data_template".`
```
test:
  sequence:
    - event: flow_test
      event_data:
        state: "on"
```

I hope this can be fixed easily because it is really annoying :)
