### ISSUE TITLE
Lovelace Entities Card: Property attribute is not allowed

### ISSUE THREAD

**Issue by colemamd** [keesschollaart81/vscode-home-assistant#471]
1.  Is it an YAML parsing error?

Don't think so

2.  Is a HA scheme error?

Not sure if this is a TS error. If so I will make PR on appropriate repo.

Receive Property attribute is not allowed in my entities cards.

```
 {
	"resource": "/hacc/homeassistant/config/ui-lovelace.yaml",
	"owner": "_generated_diagnostic_collection_name_#0",
	"severity": 8,
	"message": "Property attribute is not allowed.",
	"startLineNumber": 264,
	"startColumn": 11,
	"endLineNumber": 264,
	"endColumn": 20
}
```

```
views:
    - title: fail2ban
      type: entities
      entities:
        - type: attribute
          entity: sensor.fail2ban_hass_iptables
          attribute: current_bans
          name: "HASS current bans"
        - type: attribute
          entity: sensor.fail2ban_hass_iptables
          attribute: total_bans
          name: "HASS total bans"
        - type: attribute
          entity: sensor.fail2ban_nginx_badbots
          attribute: current_bans
          name: "nginx badbots current bans"
        - type: attribute
          entity: sensor.fail2ban_nginx_badbots
          attribute: total_bans
          name: "nginx badbots total bans"
        - type: attribute
          entity: sensor.fail2ban_nginx_botsearch
          attribute: current_bans
          name: "nginx botsearch current bans"
        - type: attribute
          entity: sensor.fail2ban_nginx_botsearch
          attribute: total_bans
          name: "nginx botsearch total bans"
        - type: attribute
          entity: sensor.fail2ban_nginx_http_auth
          attribute: current_bans
          name: "nginx http auth current bans"
        - type: attribute
          entity: sensor.fail2ban_nginx_http_auth
          attribute: total_bans
          name: "nginx http auth total bans"
        - type: attribute
          entity: sensor.fail2ban_ssh
          attribute: current_bans
          name: "ssh current bans"
        - type: attribute
          entity: sensor.fail2ban_ssh
          attribute: total_bans
          name: "ssh total bans"
      show_header_toggle: false
```

https://github.com/colemamd/homeassistant/blob/master/ui-lovelace.yaml
