### ISSUE TITLE
Numeric state with proximity sensors results in YAML error

### ISSUE THREAD

**Issue by alex3305** [keesschollaart81/vscode-home-assistant#472]
I get an error when using `numeric_state` with a `proximity` sensor. Snippet:

```YAML
away:
  alias: Away
  sequence:
    - condition: numeric_state
      entity_id: proximity.home
      above: 50
```

Will result in the following error:

![image](https://user-images.githubusercontent.com/5155694/89767596-8ec25100-dafa-11ea-8d03-ffb0ecffbe81.png)
