### ISSUE TITLE
Numeric state trigger results in YAML error

### ISSUE THREAD

**Issue by bullb0g** [keesschollaart81/vscode-home-assistant#473]
I have an automation that is triggered by a counter using `numeric_state`.
 
```YAML
automation:
  - id: 2cd647f2-8a40-4324-aa14-e464f584ebb6
    alias: "Vacuum - Empty bin"
    trigger:
      - platform: numeric_state
        entity_id: counter.empty_bin
        below: 1
    action:
      - service: persistent_notification.create
        data:
          title: "Vacuum cleaner"
          message: "The dust bin must be emptied"
          notification_id: empty_dust_bin
```
It gives the following problem:
String does not match the pattern of "^sensor\.(?!_)[\da-z_]+(?<!_)\s?(?:,\s?sensor\.(?!_)[\da-z_]+(?<!_))*$".

Possibly related to #472?
