### ISSUE TITLE
`Incorrect type. Expected "object".` with included scripts

### ISSUE THREAD

**Issue by pho3nixf1re** [keesschollaart81/vscode-home-assistant#483]
I am including my scripts like so:

```yml
script: !include_dir_named scripts
```

See: https://github.com/pho3nixf1re/feliciterra-home-assistant/blob/924238110829a375c63d750e3deaeba3604a37d1/configuration.yaml#L89

And in the script file itself I am receiving this error now, `Incorrect type. Expected "object".`. My scripts run fine so I'm not sure if this error is correct. It did not always have this error but I am unsure when it was introduced. An example script file can be [viewed here](https://github.com/pho3nixf1re/feliciterra-home-assistant/blob/f22744dad09b3935bd382e99ad6fecb6f36d2421/scripts/goodmorning.yaml).

```yml
sequence:
  - service: alarm_control_panel.alarm_disarm
    entity_id: alarm_control_panel.home_alarm
```

**Comment by pho3nixf1re** [comment]
I have looked around in the TS types that generate the schemas and I do not see why this is not working. Maybe I need to manually do something in my local setup to regenerate the schema definitions?

**Comment by smkelly** [comment]
I am also seeing this. All of my scripts are includes and the error starts after "sequence:".

Example:

```yaml
alias: "Restart HASS"
sequence:
  - service: homeassistant.restart

```

In this, the third line is marked as an error:
	Incorrect type. Expected "object".

**Comment by djiest** [comment]
I have the same issue

# Problem/Motivation
I use seperate automation files in subfolders, not the default automations.yaml. In these files I get a lot of syntax errors 

## Expected behavior
When placing the same code in the default automation.yaml in the root, I get no syntax errors


## Steps to reproduce
See the screenshots
Default automations.yaml
![image](https://user-images.githubusercontent.com/1582516/92304358-7caec380-ef7d-11ea-917d-a131c901bdb2.png)

automations.yaml in includes/automations/automation.yaml
![image](https://user-images.githubusercontent.com/1582516/92304420-19716100-ef7e-11ea-8738-f8736726754c.png)

**Comment by smkelly** [comment]
Just FYI, I'm still seeing this behavior in 1.9.0. However, I'm only seeing it after/within "sequence" blocks in scripts.

**Comment by frenck** [comment]
Yes, @smkelly, this issue hasn't been resolved yet.

**Comment by Cheerion** [comment]
## The problem

  I use the approach with packages to keep my configuration.yaml clean. 
Since some time the Microsoft Visual Code add-on highlights piece of code in red with the message 'Incorrect type. Expected "Object".' underneath the highlighted block of text.

It happens with scripts and input_selects. Automations (f.e.) run without this highlighted text. 

When I run the config checker, no errors are mentioned.


## Environment
  Home Assistant 0.118.1

- Add-on with the issue: Microsoft Visual Code
- Add-on release with the issue: 2.8.2
- Last working add-on release (if known): I don't know
- Operating environment (OS/Supervised): Supervised

## Problem-relevant configuration
configuration.yaml
 ```yaml
homeassistant:
  # Load packages
  packages: !include_dir_named integrations
```

Directory integrations has a script.yaml file:
```yaml
script: !include_dir_named ../scripts
```

In the scripts folder, I have several files that show encouter the bug mentioned above. An example:
```yaml
---
alias: Speel radiostation op media player naar keuze
description: Play radio station on media player
mode: single
sequence:
  - service: media_player.volume_set
    data:
      entity_id: media_player.google_home_huiskamer
      volume_level: "0.25"
  - service: media_player.play_media
    data:
      media_content_id: https://s43.myradiostream.com/18192/listen.mp3
      media_content_type: audio/mp4
      entity_id: media_player.google_home_huiskamer
```
The highlighted text starts at the first service entry. Underneath that last line, Incorrect type. Expected "Object" is mentioned.


```yaml

```

## Traceback/Error logs


```txt

```

## Additional information

**Comment by oncleben31** [comment]
Same problem here.

**Comment by browetd** [comment]
Same problem here but with lovelace files. 
There is an error message for every view contained in a file. I am storing the lovelace files into /config/lovelace (I am running supervisor 2020.12.7 + HA 2020.12.1 + code-server 3.7.4 and VS code 1.51.1).  Same approach used for automations (automations files stored in /config/automations) but without errors.
The ui-lovelace.yaml is just one line: "views: !include_dir_merge_list lovelace/"
It is working fine in home-assistant (no error and display is as expected)
Here is an example of the error message:

![Sans titre](https://user-images.githubusercontent.com/46415133/103247460-426f9480-4967-11eb-9614-60c250522cff.png)

**Comment by einarsi** [comment]
This is still an issue when using 
```script: !include_dir_named ../scripts```
Everything starting at the first ```service:``` entry and below is highlighted as an error. An error about missing sequence also pops up when using ```fields:``` and ```variables:```

A workaround seems to be to instead use
```script: !include_dir_merge_named ../scripts```
and include the name of the script in the script files. It's redundant, but seems to be working. I.e. for a script file sunlight.yaml which begins like this:
```
alias: sunlight
description: Applies the current state of the sun (circadian lighting) to given entities
mode: parallel
max: 100
(etc...)
```
add a label at the top and indent the rest of the file contents like so:
```
sunlight:
  alias: sunlight
  description: Applies the current state of the sun (circadian lighting) to given entities
  mode: parallel
  max: 100
  (etc...)
```
