### ISSUE TITLE
Incorrect error flag for lovelace entity filter card

### ISSUE THREAD

**Issue by metbril** [keesschollaart81/vscode-home-assistant#52]
When using the entity filter card is used, errors are raised for some card properties:

<img width="614" alt="Schermafbeelding 2019-07-20 om 09 57 59" src="https://user-images.githubusercontent.com/559346/61576061-062ed800-aad5-11e9-89aa-f7af07315d94.png">

Example code:

```yaml
  - type: entity-filter
    entities:
      - entity: binary_sensor.frontdoor_contact_sensor
      - entity: binary_sensor.master_bedroom_outside_door_sensor
        name: Balkondeur
    state_filter:
      - 'on'
    card:
      type: glance
      title: Open contacten
      show_state: false
    show_empty: false
```
