### ISSUE TITLE
Add support for attributes in (numeric) state conditions

### ISSUE THREAD

**Issue by frenck** [keesschollaart81/vscode-home-assistant#532]
Home Assistant 0.115 adds support for having automation/script conditions on attribute values:

```yaml
- condition: state
  entity_id: light.hue
  attribute: hue_group
  state: "on"
```

```yaml
- condition: numeric_state
  entity_id: sensor.temperature
  attribute: outside
  above: 20
```

Upstream PR: https://github.com/home-assistant/core/pull/39050
