### ISSUE TITLE
Add support for attributes in state/numeric state trigger

### ISSUE THREAD

**Issue by frenck** [keesschollaart81/vscode-home-assistant#533]
Home Assistant 0.115 will add support for adding (numeric) state triggers based on an entity attribute.

```yaml
trigger:
  - platform: state
    entity_id: climate.living_room
    from: "off"
    to: "heat"
    attribute: havc_mode
```

```yaml
trigger:
  - platform: numeric_state
    entity_id: climate.living_room
    attribute: temperature
    above: 20
```

Upstream PR: <https://github.com/home-assistant/core/pull/39238>
