### ISSUE TITLE
Add support for new `wait_for_trigger` action

### ISSUE THREAD

**Issue by frenck** [keesschollaart81/vscode-home-assistant#534]
Home Assistant 0.115 introduces support for a new action `wait_for_trigger`

```yaml
automation:
  - trigger:
      - platform: state
        entity_id: binary_sensor.gate1
        to: 'on'
        for: 1
    mode: restart
    action:
      - wait_for_trigger:
          - platform: state
            entity_id: binary_sensor.gate2
            to: 'on'
            for: 1
        timeout: 10
        continue_on_timeout: false
      - service: notify.notify
        data:
          message: Someone just entered the yard!
```

Upstream PR: <https://github.com/home-assistant/core/pull/38075>
