### ISSUE TITLE
Time trigger can also accept an input_datetime Entity ID

### ISSUE THREAD

**Issue by frenck** [keesschollaart81/vscode-home-assistant#535]
As of Home Assistant 0.115, a time trigger can also accept an input_datetime Entity ID.

We need to make sure the schema allows for this.

```yaml
trigger:
  platform: time
  at: input_datetime.bedroom_alarm_clock_time
```

Upstream PR: https://github.com/home-assistant/core/pull/38698
