### ISSUE TITLE
Add shorthand notation for Template conditions

### ISSUE THREAD

**Issue by frenck** [keesschollaart81/vscode-home-assistant#595]
Home Assistant 0.115 adds support for shorthand condition template notations.

See upstream PR: <https://github.com/home-assistant/core/pull/39705>

Basically it allows for:

```yaml
conditions: {{ template }}
```

Or combined in a list of conditions:

```yaml
conditions:
  - {{ template }}
  - condition: state
    ...
```

More examples:

```yaml
automation:
  - alias: test
    trigger:
      ...
    condition: "{{ is_state('input_boolean.go', 'on') }}"
    action:
      ...
```

```yaml
automation:
  - alias: test
    trigger:
      ...
    condition:
      - "{{ is_state('input_boolean.go', 'on') }}"
      - condition: state
        ...
      - "{{ is_state('input_boolean.stop', 'off') }}"
    action:
      ...
```

```yaml
- choose:
    - conditions: "{{ trigger.to_state.state == 'home' }}"
      sequence:
        - ...
    - conditions: 
        - "{{ trigger.to_state.state == 'office' }}"
        - condition: state
          ...
      sequence:
        - ...
```

```yaml
- repeat:
    while: "{{ is_state('input_boolean.go', 'on') }}"
    sequence:
      - ...
- repeat:
    while: 
      - "{{ is_state('input_boolean.go', 'on') }}"
      - condition: state
        ...
    sequence:
      - ...
```

```yaml
- condition: not
  conditions: "{{ is_state('input_boolean.go', 'on') }}"
```

```yaml
- condition: or
  conditions:
    - "{{ is_state('input_boolean.go', 'on') }}"
    - condition: state
      ...
```
