### ISSUE TITLE
Time condition can also accept an input_datetime Entity ID

### ISSUE THREAD

**Issue by frenck** [keesschollaart81/vscode-home-assistant#596]
Time conditions can also accept an input_datetime Entity IDs, which makes it really simple to check against a date-time. This is scheduled for Home Assistant 0.115

Upstream PR: <https://github.com/home-assistant/core/pull/39676>

Old:

```yaml
- condition: template
  value_template: "{{ states('sensor.time') == (state_attr('input_datetime.house_silent_hours_end', 'timestamp') | int | timestamp_custom('%H:%M', False)) }}"
```

New:

```yaml
- condition: time
  after: input_datetime.house_silent_hours_end
```

or even:

```yaml
- condition: time
  after: input_datetime.house_silent_hours_start
  before: input_datetime.house_silent_hours_end
```
