### ISSUE TITLE
Numeric state condition can also accept input_number entity ID

### ISSUE THREAD

**Issue by frenck** [keesschollaart81/vscode-home-assistant#597]
Home Assistant 0.115 adds support for using `input_number` entities (number helpers) with the numeric_state conditions.

parent PR: <https://github.com/home-assistant/core/pull/39680>

For example:

```yaml
- condition: numeric_state
  entity_id: climate.living_room_thermostat
  attribute: temperature
  above: input_number.temperature_threshold_low
  below: input_number.temperature_threshold_high
```
