### ISSUE TITLE
State condition can also accept an input_* Entity ID as state value

### ISSUE THREAD

**Issue by frenck** [keesschollaart81/vscode-home-assistant#598]
Home Assistant 0.115 allows for using `input_*` entities (helpers) with state conditions as a value.

Upstream PR: <https://github.com/home-assistant/core/pull/39691>

Examples:

```yaml
- condition: state
  entity_id: sensor.test
  state: input_text.test
```

```yaml
- condition: state
  entity_id: sensor.test
  state: input_select.test
```

```yaml
- condition: state
  entity_id: sensor.test
  state: input_number.test
```

```yaml
- condition: state
  entity_id: light.test
  state: input_boolean.test
```
