### ISSUE TITLE
Support 'for' without setting the 'to'-state in automation state triggers

### ISSUE THREAD

**Issue by frenck** [keesschollaart81/vscode-home-assistant#601]
As of Home Assistant 0.115, having `to` in a state trigger when using `for`, is no longer required.

Upstream PR: <https://github.com/home-assistant/core/pull/39730>

```yaml
trigger:
  - platform: state
    entity_id: binary_sensor.motion
    for:
      seconds: 10
```
