### ISSUE TITLE
YAML auto indentation issue

### ISSUE THREAD

**Issue by VDRainer** [keesschollaart81/vscode-home-assistant#622]
After reading 1 & 2 👆, type your issue here and please include the related YAML code like this:

Auto indentation adds indents after new lines, also on copy and pasting code blocks, indentations are added.

```YAML
every:
   - yaml
```

and/or point to a repository containing your Home Assistant Configuration
https://github.com/hassio-addons/addon-vscode/issues/128

**Comment by frenck** [comment]
"Auto indentation adds indents after new lines"

That is the correct behavior...

**Comment by VDRainer** [comment]
... **after** new lines.
I think the gif makes the issue clear?

**Comment by frenck** [comment]
gif?

I only see this text:

![image](https://user-images.githubusercontent.com/195327/93053684-7cdb4d00-f668-11ea-980d-cdef02a22be8.png)


Maybe a rendering issue in my browser or GitHub?

**Comment by VDRainer** [comment]
Well, it's in the issue from the addon-vscode that i linked to.
But here once again.
![yaml_indentation](https://user-images.githubusercontent.com/26381449/93054098-24587f80-f669-11ea-8185-99c7ab40d730.gif)

**Comment by CeeWeasel** [comment]
I have been battling this issue for a while now as well. I assumed that my settings for yaml files, the home assistant extension, and/or vscode were just broken somehow, so I finally got used to unindenting everything I pasted.

Some notes:
```
  If you keep pasting an indented item, it will indent it again.
    If you keep pasting an indented item, it will indent it again.
        If you keep pasting an indented item, it will indent it again.
          If you keep pasting an indented item, it will indent it again.
```
You get the idea...

There are also times where the first line in a block of pasted code will be indented an extra time, compared to the rest of the code. For example, if I were to just copy the service chunk from below:
```
action:
  - service: input_select.select_option
    data:
      entity_id: input_select.broken_indentions
      option: 'off'
```

it would look like this when pasted:
```
action:
    - service: input_select.select_option
    data:
      entity_id: input_select.broken_indentions
      option: 'off'
```
