### ISSUE TITLE
Property name is not allowed for media-control card

### ISSUE THREAD

**Issue by definitio** [keesschollaart81/vscode-home-assistant#641]
```YAML
      - type: media-control
        entity: media_player.multiroom
        name: Multi-room
```
Error:
`Property name is not allowed.`
