### ISSUE TITLE
!secret values in zone trigger create a warning

### ISSUE THREAD

**Issue by jokerigno** [keesschollaart81/vscode-home-assistant#650]
Hi,

I'm using a !secret inside an automation using the zone trigger. VS tells me that I should use only device tracker while the automation posted below works well in HA (I've tested it)
```YAML
my automation trigger:
  - id: da_borello_hub
    alias: Da Borello
    initial_state: true
    trigger:
      platform: zone
      entity_id: !secret location_tracker_hub
      zone: zone.da_borello
      event: enter
```
Can you please fix it?

Thank you for you work! It made my journey to my smart home more easy and fun!
