### ISSUE TITLE
light-group auto-fill is incorrect

### ISSUE THREAD

**Issue by fribse** [keesschollaart81/vscode-home-assistant#703]
After reading 1 & 2 👆, type your issue here and please include the related YAML code like this:
I'm not sure where to fix this, so I'll create an issue here.
When I enter a light with platform group I write
```YAML
light:
  platform: group
```
and press enter, and vscode automatically fills
```YAML
  - platform: group id
    name: group name
    view: no
    entities:
      - 
```
As I read the documentation platform is group, not group id, and view is no longer valid for HA.
