### ISSUE TITLE
Problem with mqtt_room validation

### ISSUE THREAD

**Issue by the-mentor** [keesschollaart81/vscode-home-assistant#704]
I'm seeing the following issue when adding the blow code to my yaml configuration.
HA server check validates successfully so it seems to be related to VScode's validation

```YAML
  - platform: mqtt_room
    device_id: 2C3C037B41A1 # Match the Bluetooth MAC address of the device
    name: 'Test BT Headphones'
    state_topic: 'room_presence'
    timeout: 60
    away_timeout: 120
   - yaml
```

![image](https://user-images.githubusercontent.com/11185446/95460586-d3912980-097d-11eb-8547-58c9a7f85b0a.png)

Thanks.
-DM
