### ISSUE TITLE
Property mode is not allowed for input_number

### ISSUE THREAD

**Issue by definitio** [keesschollaart81/vscode-home-assistant#705]
```YAML
input_number:
  batteries_low_level:
    min: 0
    max: 100
    mode: box
```
Error:
`Property mode is not allowed.`
