### ISSUE TITLE
Schema for input_number requires boolean for initial value

### ISSUE THREAD

**Issue by trdischat** [keesschollaart81/vscode-home-assistant#716]
The schema for `input_number` complains that the initial value specified below should be a boolean.  It should be a number.
```YAML
input_number:
  summer_daily_baseline:
    name: Summer baseline allowance (kWh/d)
    mode: box
    min: 0
    max: 100
    unit_of_measurement: "kWh"
    initial: 9.9
```
