### ISSUE TITLE
missing property "off delay" required when its optional

### ISSUE THREAD

**Issue by djryan012** [keesschollaart81/vscode-home-assistant#752]
MQTT Binary Sensor

Please include the related YAML code:

```YAML
#WallPanel Motion Detection
- platform: mqtt
  state_topic: 'wallpanel/mywallpanel/sensor/motion'
  name: 'Wallpanel Motion Sensor'
  payload_on: '{"value":true}'
  payload_off: '{"value":false}'
  device_class: motion
```

Find my Home Assistant Configuration here:
[Link to Home Assistant Configuration](<https://github.com/djryan012/homeassistant-config>)

Extension runs in:
- [X] VS Code for Desktop 
- [ ] Hassio Add-on 
- [ ] Visual Studio Online
- [ ] Other: 

I'm running VS Code on:
- [X] Windows 
- [ ] Mac 
- [ ] Linux 

I'm accessing my files:
- [ ] From local disk 
- [ ] Via remote SSH 
- [X] Smb
- [ ] Other:
