### ISSUE TITLE
initial: tag for input_number: takes a numeric value and the extension claims that it should be a boolean

### ISSUE THREAD

**Issue by rccoleman** [keesschollaart81/vscode-home-assistant#781]
```YAML
max_water_temp:
  name: Max Water Temp
  initial: 100.0
  min: 0.0
  max: 255.0
```

![image](https://user-images.githubusercontent.com/860888/97612921-4289fd00-19d5-11eb-8b6a-1e5e63eb8c3d.png)

`initial:` is also used in various other places, such as automations, where boolean is expected, but it should accept a numeric value when used in an `input_number` context.

`input_number` docs: https://www.home-assistant.io/integrations/input_number/
