### ISSUE TITLE
Property media_dirs is not allowed.

### ISSUE THREAD

**Issue by vanlooverenkoen** [keesschollaart81/vscode-home-assistant#812]
Please include the related YAML code:

```YAML
homeassistant:
  media_dirs:
    custom: /config/media
```

gives me this error:
```
Property media_dirs is not allowed.
```
