### ISSUE TITLE
Merge key error

### ISSUE THREAD

**Issue by definitio** [keesschollaart81/vscode-home-assistant#86]
```
        entities:
          - entity: light.lroom_light
            <<: &ceiling-light
              type: custom:slider-entity-row
              toggle: false
              hide_state: true
```
`<<: &ceiling-light` is highlighted: `Property << is not allowed.`
