### ISSUE TITLE
Using !include causes errors

### ISSUE THREAD

**Issue by kloggy** [keesschollaart81/vscode-home-assistant#875]
1.  Is it an YAML parsing error?

I don't think so,

![image](https://user-images.githubusercontent.com/38220016/101608855-27f86a00-39fe-11eb-90f5-deb40515874b.png)

2.  Is a HA scheme error?

I think so but I am not sure I know how to fix it myself.

I hope the following is enough information. If not I can post more.

My Lovelace files affected by this are long but here is the part where the error first occurs:

```YAML
title: System Information
path: system_information
icon: mdi:desktop-classic

cards:

  - type: vertical-stack
    cards:

      - type: conditional
        conditions:
          - entity: binary_sensor.water_softener_salt
            state: "on"
        card:
          !include
          - templates/button_title.yaml
          - title: WATER SOFTENER SALT LEVEL WARNING
            font_family: Oswald

      - type: conditional
        conditions:
          - entity: binary_sensor.water_softener_salt
            state: "on"
        card:
          type: entities
          show_header_toggle: false
          entities:
            - entity: binary_sensor.water_softener_salt
              icon: mdi:shaker-outline
          style: |
            ha-card {
              color: rgb(255, 165, 0);
              --paper-item-icon-color: rgb(255, 165, 0);
            }

```

![image](https://user-images.githubusercontent.com/38220016/101609422-ddc3b880-39fe-11eb-9f68-9563d98e4236.png)

It causes multiple errors in the file:
![image](https://user-images.githubusercontent.com/38220016/101609241-9d643a80-39fe-11eb-94b0-331ed4ebed57.png)
