### ISSUE TITLE
Mulitple package definitions seen as error

### ISSUE THREAD

**Issue by ed-holland** [keesschollaart81/vscode-home-assistant#89]
I'm using packages to group configurations. Only one string is expected although more are possible.

```
Example:
  packages:
    shelly: !include package/shelly/shelly_package.yaml
    sonoff: !include package/sonoff/sonoff_package.yaml
    glance: !include package/glance/glance_package.yaml
```

Error message:
Incorrect type. Expected "string"
