### ISSUE TITLE
Deprecated warning for resources in ui-lovelace.yaml but they are not deprecated

### ISSUE THREAD

**Issue by wsw70** [keesschollaart81/vscode-home-assistant#907]
The `resources` section of `ui-lovelace.yaml` is highlighted as deprecated but it seems that it is not. I tried to remove the entries (installed via HACS) and the integrations are not recognized afterward. Adding the resources is explicitely mentioned in the installation documentation of the extensions (again, as part of the HACS installation)

![image](https://user-images.githubusercontent.com/1345886/103368669-77472d00-4ac8-11eb-88c5-ceab5cef0f82.png)

```YAML
# example of resource highlighted as deprecated
resources:
  - url: /hacsfiles/rgb-light-card/card.js
    type: module
```
